// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace uFrameECSExample {
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;
    using uFrame.ECS;
    using uFrame.ECS.Components;
    using uFrame.Json;
    using UniRx;
    using UnityEngine;
    
    
    [uFrame.Attributes.ComponentId(12)]
    [uFrame.Attributes.uFrameIdentifier("d7f8c2c6-a31f-47cb-9bf0-6fa6f328600b")]
    public partial class DestroyOnCollision : uFrame.ECS.Components.EcsComponent {
        
        public override int ComponentId {
            get {
                return 12;
            }
        }
    }
}
