// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace uFrameECSExample {
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;
    using uFrame.ECS;
    using uFrame.ECS.Components;
    using uFrame.Json;
    using UniRx;
    using UnityEngine;
    
    
    [uFrame.Attributes.ComponentId(13)]
    [uFrame.Attributes.uFrameIdentifier("9be1dd2c-84ac-42b7-b4b8-1c80e1462b03")]
    public partial class EffectOnDestroy : uFrame.ECS.Components.EcsComponent {
        
        [UnityEngine.SerializeField()]
        private GameObject _Prefab;
        
        private Subject<PropertyChangedEvent<GameObject>> _PrefabObservable;
        
        private PropertyChangedEvent<GameObject> _PrefabEvent;
        
        public override int ComponentId {
            get {
                return 13;
            }
        }
        
        public IObservable<PropertyChangedEvent<GameObject>> PrefabObservable {
            get {
                return _PrefabObservable ?? (_PrefabObservable = new Subject<PropertyChangedEvent<GameObject>>());
            }
        }
        
        public GameObject Prefab {
            get {
                return _Prefab;
            }
            set {
                SetPrefab(value);
            }
        }
        
        public virtual void SetPrefab(GameObject value) {
            SetProperty(ref _Prefab, value, ref _PrefabEvent, _PrefabObservable);
        }
    }
}
