// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace uFrameECSExample {
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;
    using uFrame.ECS;
    using uFrame.ECS.Components;
    using uFrame.Json;
    using UniRx;
    using UnityEngine;
    
    
    [uFrame.Attributes.ComponentId(21)]
    [uFrame.Attributes.uFrameIdentifier("6dc20d87-2a14-4e88-a34f-fbbb9a922163")]
    public partial class GameOverOnCollision : uFrame.ECS.Components.EcsComponent {
        
        public override int ComponentId {
            get {
                return 21;
            }
        }
    }
}
