// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace uFrameECSExample {
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;
    using uFrame.ECS;
    using uFrame.ECS.Components;
    using uFrame.Json;
    using UniRx;
    using UnityEngine;
    
    
    [uFrame.Attributes.ComponentId(1)]
    [uFrame.Attributes.uFrameIdentifier("ce9fce25-f1ac-4383-bb98-7f3473b44d70")]
    public partial class Gunner : uFrame.ECS.Components.EcsComponent {
        
        [UnityEngine.SerializeField()]
        private Gun[] _Guns;
        
        private ReactiveCollection<Gun> _GunsReactive;
        
        public override int ComponentId {
            get {
                return 1;
            }
        }
        
        public ReactiveCollection<Gun> Guns {
            get {
                if (_GunsReactive == null) {
                    _GunsReactive = new ReactiveCollection<Gun>(_Guns ?? new Gun[] { });
                }
                return _GunsReactive;
            }
        }
    }
}
