// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace uFrameECSExample {
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;
    using uFrame.ECS;
    using uFrame.ECS.Components;
    using uFrame.Json;
    using UniRx;
    using UnityEngine;
    
    
    [uFrame.Attributes.ComponentId(17)]
    [uFrame.Attributes.uFrameIdentifier("d002f4ab-c10e-4168-97cf-6c1b3707f320")]
    public partial class MenuUI : uFrame.ECS.Components.EcsComponent {
        
        public override int ComponentId {
            get {
                return 17;
            }
        }
    }
}
