// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace uFrameECSExample {
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;
    using uFrame.ECS;
    using uFrame.ECS.Components;
    using uFrame.Json;
    using UniRx;
    using UnityEngine;
    
    
    [uFrame.Attributes.ComponentId(18)]
    [uFrame.Attributes.uFrameIdentifier("09284c60-50e8-447b-a43b-75613a84aba9")]
    public partial class PlayGameButton : uFrame.ECS.Components.EcsComponent {
        
        [UnityEngine.SerializeField()]
        private GameObject[] _InstantiateItems;
        
        private ReactiveCollection<GameObject> _InstantiateItemsReactive;
        
        public override int ComponentId {
            get {
                return 18;
            }
        }
        
        public ReactiveCollection<GameObject> InstantiateItems {
            get {
                if (_InstantiateItemsReactive == null) {
                    _InstantiateItemsReactive = new ReactiveCollection<GameObject>(_InstantiateItems ?? new GameObject[] { });
                }
                return _InstantiateItemsReactive;
            }
        }
    }
}
