// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace uFrameECSExample {
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;
    using uFrame.ECS;
    using uFrame.ECS.Components;
    using uFrame.Json;
    using UniRx;
    using UnityEngine;
    
    
    [uFrame.Attributes.ComponentId(10)]
    [uFrame.Attributes.uFrameIdentifier("972c62a6-bc0f-4a72-b152-a5d88d96db11")]
    public partial class RandomRotation : uFrame.ECS.Components.EcsComponent {
        
        [UnityEngine.SerializeField()]
        private Single _Tumble;
        
        private Subject<PropertyChangedEvent<Single>> _TumbleObservable;
        
        private PropertyChangedEvent<Single> _TumbleEvent;
        
        public override int ComponentId {
            get {
                return 10;
            }
        }
        
        public IObservable<PropertyChangedEvent<Single>> TumbleObservable {
            get {
                return _TumbleObservable ?? (_TumbleObservable = new Subject<PropertyChangedEvent<Single>>());
            }
        }
        
        public Single Tumble {
            get {
                return _Tumble;
            }
            set {
                SetTumble(value);
            }
        }
        
        public virtual void SetTumble(Single value) {
            SetProperty(ref _Tumble, value, ref _TumbleEvent, _TumbleObservable);
        }
    }
}
