// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace uFrameECSExample {
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;
    using uFrame.ECS;
    using uFrame.ECS.Components;
    using uFrame.Json;
    using UniRx;
    using UnityEngine;
    using UnityEngine.UI;
    
    
    [uFrame.Attributes.ComponentId(14)]
    [uFrame.Attributes.uFrameIdentifier("bd8bc42d-7391-4c6c-b6a3-b178171a142c")]
    public partial class ScoreText : uFrame.ECS.Components.EcsComponent {
        
        [UnityEngine.SerializeField()]
        private Text _Text;
        
        private Subject<PropertyChangedEvent<Text>> _TextObservable;
        
        private PropertyChangedEvent<Text> _TextEvent;
        
        public override int ComponentId {
            get {
                return 14;
            }
        }
        
        public IObservable<PropertyChangedEvent<Text>> TextObservable {
            get {
                return _TextObservable ?? (_TextObservable = new Subject<PropertyChangedEvent<Text>>());
            }
        }
        
        public Text Text {
            get {
                return _Text;
            }
            set {
                SetText(value);
            }
        }
        
        public virtual void SetText(Text value) {
            SetProperty(ref _Text, value, ref _TextEvent, _TextObservable);
        }
    }
}
