// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace uFrame.MVVM {
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;
    using uFrame.Editor.Graphs.Data;
    using uFrame.Editor.GraphUI.ViewModels;
    using uFrame.Editor.Platform;
    
    
    public class ServiceNodeViewModelBase : uFrame.Editor.GraphUI.ViewModels.GenericNodeViewModel<uFrame.Editor.Graphs.Data.GenericNode> {
        
        public ServiceNodeViewModelBase(ServiceNode graphItemObject, uFrame.Editor.GraphUI.ViewModels.DiagramViewModel diagramViewModel) : 
                base(graphItemObject, diagramViewModel) {
        }
        
        public override uFrame.Editor.Platform.NodeStyle NodeStyle {
            get {
                return NodeStyle.Normal;
            }
        }
    }
    
    public class ComputedPropertyNodeViewModelBase : uFrame.Editor.GraphUI.ViewModels.GenericNodeViewModel<uFrame.Editor.Graphs.Data.GenericNode> {
        
        public ComputedPropertyNodeViewModelBase(ComputedPropertyNode graphItemObject, uFrame.Editor.GraphUI.ViewModels.DiagramViewModel diagramViewModel) : 
                base(graphItemObject, diagramViewModel) {
        }
        
        public override uFrame.Editor.Platform.NodeStyle NodeStyle {
            get {
                return NodeStyle.Normal;
            }
        }
    }
    
    public class SimpleClassNodeViewModelBase : uFrame.Editor.GraphUI.ViewModels.GenericNodeViewModel<uFrame.Editor.Graphs.Data.GenericNode> {
        
        public SimpleClassNodeViewModelBase(SimpleClassNode graphItemObject, uFrame.Editor.GraphUI.ViewModels.DiagramViewModel diagramViewModel) : 
                base(graphItemObject, diagramViewModel) {
        }
        
        public override uFrame.Editor.Platform.NodeStyle NodeStyle {
            get {
                return NodeStyle.Normal;
            }
        }
    }
    
    public class SubSystemNodeViewModelBase : uFrame.Editor.GraphUI.ViewModels.GenericNodeViewModel<uFrame.Editor.Graphs.Data.GenericNode> {
        
        public SubSystemNodeViewModelBase(SubSystemNode graphItemObject, uFrame.Editor.GraphUI.ViewModels.DiagramViewModel diagramViewModel) : 
                base(graphItemObject, diagramViewModel) {
        }
        
        public override uFrame.Editor.Platform.NodeStyle NodeStyle {
            get {
                return NodeStyle.Normal;
            }
        }
    }
    
    public class ViewNodeViewModelBase : uFrame.Editor.GraphUI.ViewModels.GenericNodeViewModel<uFrame.Editor.Graphs.Data.GenericNode> {
        
        public ViewNodeViewModelBase(ViewNode graphItemObject, uFrame.Editor.GraphUI.ViewModels.DiagramViewModel diagramViewModel) : 
                base(graphItemObject, diagramViewModel) {
        }
        
        public override uFrame.Editor.Platform.NodeStyle NodeStyle {
            get {
                return NodeStyle.Normal;
            }
        }
    }
    
    public class SceneTypeNodeViewModelBase : uFrame.Editor.GraphUI.ViewModels.GenericNodeViewModel<uFrame.Editor.Graphs.Data.GenericNode> {
        
        public SceneTypeNodeViewModelBase(SceneTypeNode graphItemObject, uFrame.Editor.GraphUI.ViewModels.DiagramViewModel diagramViewModel) : 
                base(graphItemObject, diagramViewModel) {
        }
        
        public override uFrame.Editor.Platform.NodeStyle NodeStyle {
            get {
                return NodeStyle.Normal;
            }
        }
    }
    
    public class ElementNodeViewModelBase : uFrame.Editor.GraphUI.ViewModels.GenericNodeViewModel<uFrame.Editor.Graphs.Data.GenericNode> {
        
        public ElementNodeViewModelBase(ElementNode graphItemObject, uFrame.Editor.GraphUI.ViewModels.DiagramViewModel diagramViewModel) : 
                base(graphItemObject, diagramViewModel) {
        }
        
        public override uFrame.Editor.Platform.NodeStyle NodeStyle {
            get {
                return NodeStyle.Normal;
            }
        }
    }
    
    public class CommandNodeViewModelBase : uFrame.Editor.GraphUI.ViewModels.GenericNodeViewModel<uFrame.Editor.Graphs.Data.GenericNode> {
        
        public CommandNodeViewModelBase(CommandNode graphItemObject, uFrame.Editor.GraphUI.ViewModels.DiagramViewModel diagramViewModel) : 
                base(graphItemObject, diagramViewModel) {
        }
        
        public override uFrame.Editor.Platform.NodeStyle NodeStyle {
            get {
                return NodeStyle.Normal;
            }
        }
    }
    
    public class StateNodeViewModelBase : uFrame.Editor.GraphUI.ViewModels.GenericNodeViewModel<uFrame.Editor.Graphs.Data.GenericNode> {
        
        public StateNodeViewModelBase(StateNode graphItemObject, uFrame.Editor.GraphUI.ViewModels.DiagramViewModel diagramViewModel) : 
                base(graphItemObject, diagramViewModel) {
        }
        
        public override uFrame.Editor.Platform.NodeStyle NodeStyle {
            get {
                return NodeStyle.Normal;
            }
        }
    }
    
    public class MVVMNodeViewModelBase : uFrame.Editor.GraphUI.ViewModels.GenericNodeViewModel<uFrame.Editor.Graphs.Data.GenericNode> {
        
        public MVVMNodeViewModelBase(MVVMNode graphItemObject, uFrame.Editor.GraphUI.ViewModels.DiagramViewModel diagramViewModel) : 
                base(graphItemObject, diagramViewModel) {
        }
        
        public override uFrame.Editor.Platform.NodeStyle NodeStyle {
            get {
                return NodeStyle.Normal;
            }
        }
    }
    
    public class ViewComponentNodeViewModelBase : uFrame.Editor.GraphUI.ViewModels.GenericNodeViewModel<uFrame.Editor.Graphs.Data.GenericNode> {
        
        public ViewComponentNodeViewModelBase(ViewComponentNode graphItemObject, uFrame.Editor.GraphUI.ViewModels.DiagramViewModel diagramViewModel) : 
                base(graphItemObject, diagramViewModel) {
        }
        
        public override uFrame.Editor.Platform.NodeStyle NodeStyle {
            get {
                return NodeStyle.Normal;
            }
        }
    }
    
    public class StateMachineNodeViewModelBase : uFrame.Editor.GraphUI.ViewModels.GenericNodeViewModel<uFrame.Editor.Graphs.Data.GenericNode> {
        
        public StateMachineNodeViewModelBase(StateMachineNode graphItemObject, uFrame.Editor.GraphUI.ViewModels.DiagramViewModel diagramViewModel) : 
                base(graphItemObject, diagramViewModel) {
        }
        
        public override uFrame.Editor.Platform.NodeStyle NodeStyle {
            get {
                return NodeStyle.Normal;
            }
        }
    }
}
