// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace uFrameECSExample {
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;
    using uFrame.ECS;
    using uFrame.Kernel;
    
    
    #region 
static
    public class HazardsModuleExtensions {
        
        #region 
static
        public uFrame.ECS.APIs.IEcsComponentManagerOf<EnemyAI> EnemyAIManager(this uFrame.ECS.APIs.IEcsSystem system) {
            return system.ComponentSystem.RegisterComponent<EnemyAI>();
        }
        #endregion
        
        #region 
static
        public uFrame.ECS.APIs.IEcsComponentManagerOf<Projectile> ProjectileManager(this uFrame.ECS.APIs.IEcsSystem system) {
            return system.ComponentSystem.RegisterComponent<Projectile>();
        }
        #endregion
        
        #region 
static
        public uFrame.ECS.APIs.IEcsComponentManagerOf<RandomRotation> RandomRotationManager(this uFrame.ECS.APIs.IEcsSystem system) {
            return system.ComponentSystem.RegisterComponent<RandomRotation>();
        }
        #endregion
        
        #region 
static
        public uFrame.ECS.APIs.IEcsComponentManagerOf<SpawnWithRandomX> SpawnWithRandomXManager(this uFrame.ECS.APIs.IEcsSystem system) {
            return system.ComponentSystem.RegisterComponent<SpawnWithRandomX>();
        }
        #endregion
        
        #region 
static
        public uFrame.ECS.APIs.IEcsComponentManagerOf<Hazard> HazardManager(this uFrame.ECS.APIs.IEcsSystem system) {
            return system.ComponentSystem.RegisterComponent<Hazard>();
        }
        #endregion
        
        #region 
static
        public uFrame.ECS.APIs.IEcsComponentManagerOf<DestroyOnCollision> DestroyOnCollisionManager(this uFrame.ECS.APIs.IEcsSystem system) {
            return system.ComponentSystem.RegisterComponent<DestroyOnCollision>();
        }
        #endregion
        
        #region 
static
        public List<EnemyAI> EnemyAIComponents(this uFrame.ECS.APIs.IEcsSystem system) {
            return system.ComponentSystem.RegisterComponent<EnemyAI>().Components;
        }
        #endregion
        
        #region 
static
        public List<Projectile> ProjectileComponents(this uFrame.ECS.APIs.IEcsSystem system) {
            return system.ComponentSystem.RegisterComponent<Projectile>().Components;
        }
        #endregion
        
        #region 
static
        public List<RandomRotation> RandomRotationComponents(this uFrame.ECS.APIs.IEcsSystem system) {
            return system.ComponentSystem.RegisterComponent<RandomRotation>().Components;
        }
        #endregion
        
        #region 
static
        public List<SpawnWithRandomX> SpawnWithRandomXComponents(this uFrame.ECS.APIs.IEcsSystem system) {
            return system.ComponentSystem.RegisterComponent<SpawnWithRandomX>().Components;
        }
        #endregion
        
        #region 
static
        public List<Hazard> HazardComponents(this uFrame.ECS.APIs.IEcsSystem system) {
            return system.ComponentSystem.RegisterComponent<Hazard>().Components;
        }
        #endregion
        
        #region 
static
        public List<DestroyOnCollision> DestroyOnCollisionComponents(this uFrame.ECS.APIs.IEcsSystem system) {
            return system.ComponentSystem.RegisterComponent<DestroyOnCollision>().Components;
        }
        #endregion
    }
    #endregion
}
