// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace uFrameECSExample {
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;
    using uFrame.ECS.APIs;
    using uFrame.ECS.Components;
    using uFrame.ECS.Systems;
    using uFrame.Kernel;
    using uFrameECSExample;
    using UniRx;
    using UnityEngine;
    
    
    public partial class WavesGameSystemBase : uFrame.ECS.Systems.EcsSystem {
        
        private IEcsComponentManagerOf<SpawnAtInterval> _SpawnAtIntervalManager;
        
        private IEcsComponentManagerOf<WavesGame> _WavesGameManager;
        
        private IEcsComponentManagerOf<SpawnMultipleAtInterval> _SpawnMultipleAtIntervalManager;
        
        private IEcsComponentManagerOf<PointsOnDestroy> _PointsOnDestroyManager;
        
        private IEcsComponentManagerOf<PlayGameButton> _PlayGameButtonManager;
        
        private IEcsComponentManagerOf<GameOverOnCollision> _GameOverOnCollisionManager;
        
        private IEcsComponentManagerOf<ScoreText> _ScoreTextManager;
        
        private IEcsComponentManagerOf<MenuUI> _MenuUIManager;
        
        public IEcsComponentManagerOf<SpawnAtInterval> SpawnAtIntervalManager {
            get {
                return _SpawnAtIntervalManager;
            }
            set {
                _SpawnAtIntervalManager = value;
            }
        }
        
        public IEcsComponentManagerOf<WavesGame> WavesGameManager {
            get {
                return _WavesGameManager;
            }
            set {
                _WavesGameManager = value;
            }
        }
        
        public IEcsComponentManagerOf<SpawnMultipleAtInterval> SpawnMultipleAtIntervalManager {
            get {
                return _SpawnMultipleAtIntervalManager;
            }
            set {
                _SpawnMultipleAtIntervalManager = value;
            }
        }
        
        public IEcsComponentManagerOf<PointsOnDestroy> PointsOnDestroyManager {
            get {
                return _PointsOnDestroyManager;
            }
            set {
                _PointsOnDestroyManager = value;
            }
        }
        
        public IEcsComponentManagerOf<PlayGameButton> PlayGameButtonManager {
            get {
                return _PlayGameButtonManager;
            }
            set {
                _PlayGameButtonManager = value;
            }
        }
        
        public IEcsComponentManagerOf<GameOverOnCollision> GameOverOnCollisionManager {
            get {
                return _GameOverOnCollisionManager;
            }
            set {
                _GameOverOnCollisionManager = value;
            }
        }
        
        public IEcsComponentManagerOf<ScoreText> ScoreTextManager {
            get {
                return _ScoreTextManager;
            }
            set {
                _ScoreTextManager = value;
            }
        }
        
        public IEcsComponentManagerOf<MenuUI> MenuUIManager {
            get {
                return _MenuUIManager;
            }
            set {
                _MenuUIManager = value;
            }
        }
        
        public override void Setup() {
            base.Setup();
            SpawnAtIntervalManager = ComponentSystem.RegisterComponent<SpawnAtInterval>(16);
            WavesGameManager = ComponentSystem.RegisterComponent<WavesGame>(15);
            SpawnMultipleAtIntervalManager = ComponentSystem.RegisterComponent<SpawnMultipleAtInterval>(20);
            PointsOnDestroyManager = ComponentSystem.RegisterComponent<PointsOnDestroy>(19);
            PlayGameButtonManager = ComponentSystem.RegisterComponent<PlayGameButton>(18);
            GameOverOnCollisionManager = ComponentSystem.RegisterComponent<GameOverOnCollision>(21);
            ScoreTextManager = ComponentSystem.RegisterComponent<ScoreText>(14);
            MenuUIManager = ComponentSystem.RegisterComponent<MenuUI>(17);
            SpawnAtIntervalManager.CreatedObservable.Subscribe(BeginIntervalSpawnFilter).DisposeWith(this);
            PointsOnDestroyManager.RemovedObservable.Subscribe(_=>PointsOnDestroyComponentDestroyed(_,_)).DisposeWith(this);
            SpawnMultipleAtIntervalManager.CreatedObservable.Subscribe(BeginMultipleIntervalSpawnFilter).DisposeWith(this);
            this.OnEvent<uFrameECSExample.GameOver>().Subscribe(_=>{ WavesGameSystemGameOverFilter(_); }).DisposeWith(this);
            WavesGameManager.CreatedObservable.Subscribe(WavesGameCreatedFilter).DisposeWith(this);
        }
        
        protected virtual void BeginIntervalSpawn(SpawnAtInterval data, SpawnAtInterval group) {
            var handler = new BeginIntervalSpawn();
            handler.System = this;
            handler.Event = data;
            handler.Group = group;
            StartCoroutine(handler.Execute());
        }
        
        protected void BeginIntervalSpawnFilter(SpawnAtInterval data) {
            var GroupSpawnAtInterval = SpawnAtIntervalManager[data.EntityId];
            if (GroupSpawnAtInterval == null) {
                return;
            }
            if (!GroupSpawnAtInterval.Enabled) {
                return;
            }
            this.BeginIntervalSpawn(data, GroupSpawnAtInterval);
        }
        
        protected virtual void PointsOnDestroyComponentDestroyed(PointsOnDestroy data, PointsOnDestroy group) {
            var handler = new PointsOnDestroyComponentDestroyed();
            handler.System = this;
            handler.Event = data;
            handler.Group = group;
            StartCoroutine(handler.Execute());
        }
        
        protected void PointsOnDestroyComponentDestroyedFilter(PointsOnDestroy data) {
            var GroupPointsOnDestroy = PointsOnDestroyManager[data.EntityId];
            if (GroupPointsOnDestroy == null) {
                return;
            }
            if (!GroupPointsOnDestroy.Enabled) {
                return;
            }
            this.PointsOnDestroyComponentDestroyed(data, GroupPointsOnDestroy);
        }
        
        protected virtual void BeginMultipleIntervalSpawn(SpawnMultipleAtInterval data, SpawnMultipleAtInterval group) {
            var handler = new BeginMultipleIntervalSpawn();
            handler.System = this;
            handler.Event = data;
            handler.Group = group;
            StartCoroutine(handler.Execute());
        }
        
        protected void BeginMultipleIntervalSpawnFilter(SpawnMultipleAtInterval data) {
            var GroupSpawnMultipleAtInterval = SpawnMultipleAtIntervalManager[data.EntityId];
            if (GroupSpawnMultipleAtInterval == null) {
                return;
            }
            if (!GroupSpawnMultipleAtInterval.Enabled) {
                return;
            }
            this.BeginMultipleIntervalSpawn(data, GroupSpawnMultipleAtInterval);
        }
        
        protected virtual void WavesGameSystemGameOverHandler(uFrameECSExample.GameOver data, WavesGame group) {
            var handler = new WavesGameSystemGameOverHandler();
            handler.System = this;
            handler.Event = data;
            handler.Group = group;
            StartCoroutine(handler.Execute());
        }
        
        protected void WavesGameSystemGameOverFilter(uFrameECSExample.GameOver data) {
            var WavesGameItems = WavesGameManager.Components;
            for (var WavesGameIndex = 0
            ; WavesGameIndex < WavesGameItems.Count; WavesGameIndex++
            ) {
                if (!WavesGameItems[WavesGameIndex].Enabled) {
                    continue;
                }
                this.WavesGameSystemGameOverHandler(data, WavesGameItems[WavesGameIndex]);
            }
        }
        
        protected virtual void WavesGameCreated(WavesGame data, WavesGame group) {
            var handler = new WavesGameCreated();
            handler.System = this;
            handler.Event = data;
            handler.Group = group;
            StartCoroutine(handler.Execute());
        }
        
        protected void WavesGameCreatedFilter(WavesGame data) {
            var GroupWavesGame = WavesGameManager[data.EntityId];
            if (GroupWavesGame == null) {
                return;
            }
            if (!GroupWavesGame.Enabled) {
                return;
            }
            this.WavesGameCreated(data, GroupWavesGame);
        }
    }
    
    [uFrame.Attributes.uFrameIdentifier("54c25afa-7c76-4d30-96a1-2b557c8d5ec2")]
    public partial class WavesGameSystem : WavesGameSystemBase {
        
        private static WavesGameSystem _Instance;
        
        public WavesGameSystem() {
            Instance = this;
        }
        
        public static WavesGameSystem Instance {
            get {
                return _Instance;
            }
            set {
                _Instance = value;
            }
        }
    }
}
