// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace uFrameECSExample {
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;
    using uFrame.ECS;
    using uFrame.ECS.UnityUtilities;
    using uFrame.Kernel;
    using UnityEngine;
    
    
    public class BeginRandomRotation {
        
        public RandomRotation Group;
        
        private RandomRotation _Event;
        
        private uFrame.ECS.Systems.EcsSystem _System;
        
        private UnityEngine.GameObject ActionNode15_go = default( UnityEngine.GameObject );
        
        private UnityEngine.MonoBehaviour ActionNode15_component = default( UnityEngine.MonoBehaviour );
        
        private UnityEngine.Rigidbody ActionNode15_Result = default( UnityEngine.Rigidbody );
        
        private UnityEngine.Vector3 ActionNode16_Result = default( UnityEngine.Vector3 );
        
        private UnityEngine.Vector3 ActionNode17_a = default( UnityEngine.Vector3 );
        
        private float ActionNode17_b = default( System.Single );
        
        private UnityEngine.Vector3 ActionNode17_Result = default( UnityEngine.Vector3 );
        
        public RandomRotation Event {
            get {
                return _Event;
            }
            set {
                _Event = value;
            }
        }
        
        public uFrame.ECS.Systems.EcsSystem System {
            get {
                return _System;
            }
            set {
                _System = value;
            }
        }
        
        public virtual System.Collections.IEnumerator Execute() {
            ActionNode15_go = Group.Entity.gameObject;
            // ActionNode
            while (this.DebugInfo("aae77b86-d81d-49bc-a708-d6c380220df7","db177484-216a-4abd-a4aa-74bf329ecf4f", this) == 1) yield return null;
            // Visit uFrame.ECS.Actions.UnityLibrary.GetRigidbody
            ActionNode15_Result = uFrame.ECS.Actions.UnityLibrary.GetRigidbody(ActionNode15_go, ActionNode15_component);
            // ActionNode
            while (this.DebugInfo("db177484-216a-4abd-a4aa-74bf329ecf4f","3a1e5cff-ed91-4ef7-a61e-205be9952f8a", this) == 1) yield return null;
            // Visit uFrame.ECS.Actions.CreateRandoms.GetInsideSphere
            ActionNode16_Result = uFrame.ECS.Actions.CreateRandoms.GetInsideSphere();
            ActionNode17_a = ActionNode16_Result;
            ActionNode17_b = Group.Tumble;
            // ActionNode
            while (this.DebugInfo("3a1e5cff-ed91-4ef7-a61e-205be9952f8a","54017dfc-a1d8-4a05-bb68-870e9a172849", this) == 1) yield return null;
            // Visit uFrame.ECS.Actions.Vector3Library.Multiply
            ActionNode17_Result = uFrame.ECS.Actions.Vector3Library.Multiply(ActionNode17_a, ActionNode17_b);
            // SetVariableNode
            while (this.DebugInfo("54017dfc-a1d8-4a05-bb68-870e9a172849","5d10aee7-32bb-43c3-b3ff-49b396223825", this) == 1) yield return null;
            ActionNode15_Result.angularVelocity = (UnityEngine.Vector3)ActionNode17_Result;
            yield break;
        }
    }
}
