// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace uFrameECSExample {
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;
    using uFrame.ECS;
    using uFrame.ECS.APIs;
    using uFrame.ECS.UnityUtilities;
    using uFrame.Kernel;
    using UnityEngine;
    
    
    public class BeginIntervalSpawn {
        
        public SpawnAtInterval Group;
        
        private SpawnAtInterval _Event;
        
        private uFrame.ECS.Systems.EcsSystem _System;
        
        private float ActionNode11_Seconds = default( System.Single );
        
        private uFrame.ECS.APIs.IEcsComponent ActionNode11_DisposeWith = default( uFrame.ECS.APIs.IEcsComponent );
        
        private uFrame.ECS.Actions.IntervalBySeconds ActionNode11 = new uFrame.ECS.Actions.IntervalBySeconds();
        
        private System.IDisposable ActionNode11_Result = default( System.IDisposable );
        
        private UnityEngine.GameObject ActionNode12_gameObject = default( UnityEngine.GameObject );
        
        private UnityEngine.Vector3 ActionNode12_position = default( UnityEngine.Vector3 );
        
        private UnityEngine.Vector3 ActionNode12_rotation = default( UnityEngine.Vector3 );
        
        private UnityEngine.GameObject ActionNode12_Result = default( UnityEngine.GameObject );
        
        public SpawnAtInterval Event {
            get {
                return _Event;
            }
            set {
                _Event = value;
            }
        }
        
        public uFrame.ECS.Systems.EcsSystem System {
            get {
                return _System;
            }
            set {
                _System = value;
            }
        }
        
        public virtual System.Collections.IEnumerator Execute() {
            ActionNode11_Seconds = Group.Speed;
            // ActionNode
            while (this.DebugInfo("","4e6137a5-6cc8-42fb-8e85-629d509591ab", this) == 1) yield return null;
            // Visit uFrame.ECS.Actions.IntervalBySeconds
            ActionNode11.Seconds = ActionNode11_Seconds;
            ActionNode11.System = System;
            ActionNode11.Tick = ()=> { System.StartCoroutine(ActionNode11_Tick()); };
            ActionNode11.Execute();
            ActionNode11_Result = ActionNode11.Result;
            yield break;
        }
        
        private System.Collections.IEnumerator ActionNode11_Tick() {
            ActionNode11_Result = ActionNode11.Result;
            ActionNode12_gameObject = Group.Prefab;
            // ActionNode
            while (this.DebugInfo("4e6137a5-6cc8-42fb-8e85-629d509591ab","a7830d3d-1170-46e5-80e0-62044887374c", this) == 1) yield return null;
            // Visit uFrame.ECS.Actions.GameObjects.Instantiate
            ActionNode12_Result = uFrame.ECS.Actions.GameObjects.Instantiate(ActionNode12_gameObject, ActionNode12_position, ActionNode12_rotation);
            // SetVariableNode
            while (this.DebugInfo("a7830d3d-1170-46e5-80e0-62044887374c","658a30b6-015e-4213-a173-10e4cd84b79a", this) == 1) yield return null;
            ActionNode12_Result.transform.parent = (UnityEngine.Transform)Group.Parent;
            yield break;
        }
    }
}
