// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace uFrameECSExample {
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;
    using uFrame.ECS;
    using uFrame.ECS.UnityUtilities;
    using uFrame.Kernel;
    using UnityEngine;
    
    
    public class DisableUI {
        
        public WavesGame Group;
        
        private WavesGame _Event;
        
        private uFrame.ECS.Systems.EcsSystem _System;
        
        private uFrameECSExample.MenuUI LoopGroupNode39_Item = default( uFrameECSExample.MenuUI );
        
        private UnityEngine.GameObject ActionNode40_gameObject = default( UnityEngine.GameObject );
        
        private UnityEngine.MonoBehaviour ActionNode40_behaviour = default( UnityEngine.MonoBehaviour );
        
        public WavesGame Event {
            get {
                return _Event;
            }
            set {
                _Event = value;
            }
        }
        
        public uFrame.ECS.Systems.EcsSystem System {
            get {
                return _System;
            }
            set {
                _System = value;
            }
        }
        
        public virtual System.Collections.IEnumerator Execute() {
            // LoopGroupNode
            while (this.DebugInfo("f769312f-1b19-4c43-8564-3242e66bc0b5","85c81e7e-d19f-4cfa-873d-7836357a35d7", this) == 1) yield return null;
            var LoopGroupNode39_GroupComponents = System.ComponentSystem.RegisterComponent<uFrameECSExample.MenuUI>().Components;
            for (var LoopGroupNode39_ItemIndex = 0
            ; LoopGroupNode39_ItemIndex < LoopGroupNode39_GroupComponents.Count; LoopGroupNode39_ItemIndex++
            ) {
                LoopGroupNode39_Item = LoopGroupNode39_GroupComponents[LoopGroupNode39_ItemIndex];
                System.StartCoroutine(LoopGroupNode39_Next());
            }
            yield break;
        }
        
        private System.Collections.IEnumerator LoopGroupNode39_Next() {
            ActionNode40_gameObject = LoopGroupNode39_Item.gameObject;
            // ActionNode
            while (this.DebugInfo("85c81e7e-d19f-4cfa-873d-7836357a35d7","b810e010-5a71-4496-bbd5-842a98b926ba", this) == 1) yield return null;
            // Visit uFrame.ECS.Actions.GameObjects.DeactiateGameObject
            uFrame.ECS.Actions.GameObjects.DeactiateGameObject(ActionNode40_gameObject, ActionNode40_behaviour);
            yield break;
        }
    }
}
