// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace uFrameECSExample {
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;
    using uFrame.ECS;
    using uFrame.ECS.UnityUtilities;
    using uFrame.Kernel;
    using UnityEngine;
    
    
    public class GunnerInputUpdateHandler {
        
        public PlayerGunner Group;
        
        private uFrame.ECS.APIs.ISystemUpdate _Event;
        
        private uFrame.ECS.Systems.EcsSystem _System;
        
        private UnityEngine.KeyCode ActionNode36_key = default( UnityEngine.KeyCode );
        
        private UnityEngine.KeyCode EnumValueNode35 = KeyCode.Space;
        
        private bool ActionNode36_Result = default( System.Boolean );
        
        private uFrameECSExample.Gun LoopCollectionNode37_Item = default( uFrameECSExample.Gun );
        
        private uFrameECSExample.GunState EnumValueNode40 = GunState.Shooting;
        
        private uFrameECSExample.Gun LoopCollectionNode38_Item = default( uFrameECSExample.Gun );
        
        private uFrameECSExample.GunState EnumValueNode42 = GunState.Idle;
        
        public uFrame.ECS.APIs.ISystemUpdate Event {
            get {
                return _Event;
            }
            set {
                _Event = value;
            }
        }
        
        public uFrame.ECS.Systems.EcsSystem System {
            get {
                return _System;
            }
            set {
                _System = value;
            }
        }
        
        public virtual System.Collections.IEnumerator Execute() {
            ActionNode36_key = EnumValueNode35;
            // ActionNode
            while (this.DebugInfo("83d8ad23-6878-4a2c-806f-6a06a0d14dfb","155e0bed-d68e-4720-898a-a9a8cbe96ae0", this) == 1) yield return null;
            // Visit uFrame.ECS.Actions.InputLibrary.IsKeyDown
            ActionNode36_Result = uFrame.ECS.Actions.InputLibrary.IsKeyDown(ActionNode36_key, ()=> { System.StartCoroutine(ActionNode36_yes()); }, ()=> { System.StartCoroutine(ActionNode36_no()); });
            yield break;
        }
        
        private System.Collections.IEnumerator LoopCollectionNode37_Next() {
            // SetVariableNode
            while (this.DebugInfo("c9096a73-7122-40b2-9709-bc30b41da983","cb68aaa2-2333-45c6-bf87-ec8d2a0d1188", this) == 1) yield return null;
            LoopCollectionNode37_Item.State = (uFrameECSExample.GunState)EnumValueNode40;
            yield break;
        }
        
        private System.Collections.IEnumerator ActionNode36_yes() {
            // LoopCollectionNode
            while (this.DebugInfo("155e0bed-d68e-4720-898a-a9a8cbe96ae0","c9096a73-7122-40b2-9709-bc30b41da983", this) == 1) yield return null;
            for (var LoopCollectionNode37_ItemIndex = 0
            ; LoopCollectionNode37_ItemIndex < Group.Gunner.Guns.Count; LoopCollectionNode37_ItemIndex++
            ) {
                LoopCollectionNode37_Item = Group.Gunner.Guns[LoopCollectionNode37_ItemIndex];
                System.StartCoroutine(LoopCollectionNode37_Next());
            }
            yield break;
        }
        
        private System.Collections.IEnumerator LoopCollectionNode38_Next() {
            // SetVariableNode
            while (this.DebugInfo("56f547c4-2868-4c9c-830b-93e155c1f352","b8958212-4f11-4c4e-86dc-afa0b2d200db", this) == 1) yield return null;
            LoopCollectionNode38_Item.State = (uFrameECSExample.GunState)EnumValueNode42;
            yield break;
        }
        
        private System.Collections.IEnumerator ActionNode36_no() {
            // LoopCollectionNode
            while (this.DebugInfo("cb68aaa2-2333-45c6-bf87-ec8d2a0d1188","56f547c4-2868-4c9c-830b-93e155c1f352", this) == 1) yield return null;
            for (var LoopCollectionNode38_ItemIndex = 0
            ; LoopCollectionNode38_ItemIndex < Group.Gunner.Guns.Count; LoopCollectionNode38_ItemIndex++
            ) {
                LoopCollectionNode38_Item = Group.Gunner.Guns[LoopCollectionNode38_ItemIndex];
                System.StartCoroutine(LoopCollectionNode38_Next());
            }
            yield break;
        }
    }
}
