// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace uFrameECSExample {
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;
    using uFrame.ECS;
    using uFrame.ECS.UnityUtilities;
    using uFrame.Kernel;
    using UnityEngine;
    
    
    public class PointsOnDestroyComponentDestroyed {
        
        public PointsOnDestroy Group;
        
        private PointsOnDestroy _Event;
        
        private uFrame.ECS.Systems.EcsSystem _System;
        
        private uFrameECSExample.WavesGame LoopGroupNode20_Item = default( uFrameECSExample.WavesGame );
        
        private int ActionNode21_a = default( System.Int32 );
        
        private int ActionNode21_b = default( System.Int32 );
        
        private int ActionNode21_Result = default( System.Int32 );
        
        public PointsOnDestroy Event {
            get {
                return _Event;
            }
            set {
                _Event = value;
            }
        }
        
        public uFrame.ECS.Systems.EcsSystem System {
            get {
                return _System;
            }
            set {
                _System = value;
            }
        }
        
        public virtual System.Collections.IEnumerator Execute() {
            // LoopGroupNode
            while (this.DebugInfo("0f5e4b94-6070-4ecd-8398-9b080c87ab8f","9452f8e5-de78-4a7f-aa70-badfd4ffc670", this) == 1) yield return null;
            var LoopGroupNode20_GroupComponents = System.ComponentSystem.RegisterComponent<uFrameECSExample.WavesGame>().Components;
            for (var LoopGroupNode20_ItemIndex = 0
            ; LoopGroupNode20_ItemIndex < LoopGroupNode20_GroupComponents.Count; LoopGroupNode20_ItemIndex++
            ) {
                LoopGroupNode20_Item = LoopGroupNode20_GroupComponents[LoopGroupNode20_ItemIndex];
                System.StartCoroutine(LoopGroupNode20_Next());
            }
            yield break;
        }
        
        private System.Collections.IEnumerator LoopGroupNode20_Next() {
            ActionNode21_a = LoopGroupNode20_Item.Score;
            ActionNode21_b = Group.Points;
            // ActionNode
            while (this.DebugInfo("9452f8e5-de78-4a7f-aa70-badfd4ffc670","3723ec5c-7651-49f9-81b7-123352dd163d", this) == 1) yield return null;
            // Visit uFrame.ECS.Actions.IntLibrary.Add
            ActionNode21_Result = uFrame.ECS.Actions.IntLibrary.Add(ActionNode21_a, ActionNode21_b);
            // SetVariableNode
            while (this.DebugInfo("3723ec5c-7651-49f9-81b7-123352dd163d","0811d918-6965-44f6-aced-0d40c04986da", this) == 1) yield return null;
            LoopGroupNode20_Item.Score = (System.Int32)ActionNode21_Result;
            yield break;
        }
    }
}
