// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace uFrameECSExample {
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;
    using uFrame.ECS;
    using uFrame.ECS.UnityUtilities;
    using uFrame.Kernel;
    using UnityEngine;
    
    
    public class EffectOnDestroyComponentDestroyed {
        
        public EffectOnDestroy Group;
        
        private EffectOnDestroy _Event;
        
        private uFrame.ECS.Systems.EcsSystem _System;
        
        private bool ActionNode1_value = default( System.Boolean );
        
        private UnityEngine.GameObject ActionNode2_gameObject = default( UnityEngine.GameObject );
        
        private UnityEngine.Vector3 ActionNode2_position = default( UnityEngine.Vector3 );
        
        private UnityEngine.Vector3 ActionNode2_rotation = default( UnityEngine.Vector3 );
        
        private UnityEngine.GameObject ActionNode2_Result = default( UnityEngine.GameObject );
        
        public EffectOnDestroy Event {
            get {
                return _Event;
            }
            set {
                _Event = value;
            }
        }
        
        public uFrame.ECS.Systems.EcsSystem System {
            get {
                return _System;
            }
            set {
                _System = value;
            }
        }
        
        public virtual System.Collections.IEnumerator Execute() {
            ActionNode1_value = Group.IsQuiting;
            // ActionNode
            while (this.DebugInfo("3cb6bd13-e202-437e-8696-a59fef43f6a7","49fd6d63-57a5-4bbd-87e7-d55d8d784016", this) == 1) yield return null;
            // Visit uFrame.ECS.Actions.Comparisons.IsTrue
            uFrame.ECS.Actions.Comparisons.IsTrue(ActionNode1_value, ()=> { System.StartCoroutine(ActionNode1_yes()); }, ()=> { System.StartCoroutine(ActionNode1_no()); });
            yield break;
        }
        
        private System.Collections.IEnumerator ActionNode1_yes() {
            yield break;
        }
        
        private System.Collections.IEnumerator ActionNode1_no() {
            ActionNode2_gameObject = Group.Prefab;
            ActionNode2_position = Group.Entity.transform.position;
            // ActionNode
            while (this.DebugInfo("49fd6d63-57a5-4bbd-87e7-d55d8d784016","ce937078-801a-4e33-9bcd-9554f0e73fb5", this) == 1) yield return null;
            // Visit uFrame.ECS.Actions.GameObjects.Instantiate
            ActionNode2_Result = uFrame.ECS.Actions.GameObjects.Instantiate(ActionNode2_gameObject, ActionNode2_position, ActionNode2_rotation);
            yield break;
        }
    }
}
