// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace uFrameECSExample {
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;
    using uFrame.ECS;
    using uFrame.ECS.UnityUtilities;
    using uFrame.Kernel;
    using UnityEngine;
    
    
    public class PlayerSystemGameOverHandler {
        
        public WavesGame Group;
        
        private uFrameECSExample.GameOver _Event;
        
        private uFrame.ECS.Systems.EcsSystem _System;
        
        private uFrameECSExample.Player LoopGroupNode32_Item = default( uFrameECSExample.Player );
        
        private uFrame.ECS.UnityUtilities.SavePlayerData PublishEventNode34_Result = default( uFrame.ECS.UnityUtilities.SavePlayerData );
        
        public uFrameECSExample.GameOver Event {
            get {
                return _Event;
            }
            set {
                _Event = value;
            }
        }
        
        public uFrame.ECS.Systems.EcsSystem System {
            get {
                return _System;
            }
            set {
                _System = value;
            }
        }
        
        public virtual System.Collections.IEnumerator Execute() {
            // LoopGroupNode
            while (this.DebugInfo("29851530-20b9-4a19-9426-ad2813e23dde","93640c69-5df0-40c2-9844-2c2d8f217d41", this) == 1) yield return null;
            var LoopGroupNode32_GroupComponents = System.ComponentSystem.RegisterComponent<uFrameECSExample.Player>().Components;
            for (var LoopGroupNode32_ItemIndex = 0
            ; LoopGroupNode32_ItemIndex < LoopGroupNode32_GroupComponents.Count; LoopGroupNode32_ItemIndex++
            ) {
                LoopGroupNode32_Item = LoopGroupNode32_GroupComponents[LoopGroupNode32_ItemIndex];
                System.StartCoroutine(LoopGroupNode32_Next());
            }
            yield break;
        }
        
        private System.Collections.IEnumerator LoopGroupNode32_Next() {
            // SetVariableNode
            while (this.DebugInfo("93640c69-5df0-40c2-9844-2c2d8f217d41","b5763d41-0b24-49bb-bae3-50986c89e694", this) == 1) yield return null;
            LoopGroupNode32_Item.BestScore = (System.Int32)Group.Score;
            // PublishEventNode
            while (this.DebugInfo("b5763d41-0b24-49bb-bae3-50986c89e694","83d8ad23-6878-4a2c-806f-6a06a0d14dfb", this) == 1) yield return null;
            var PublishEventNode34_Event = new SavePlayerData();
            System.Publish(PublishEventNode34_Event);
            PublishEventNode34_Result = PublishEventNode34_Event;
            yield break;
        }
    }
}
