// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace uFrameECSExample {
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;
    using uFrame.ECS;
    using uFrame.ECS.UnityUtilities;
    using uFrame.Kernel;
    using UnityEngine;
    
    
    public class PlayerGunnerCreated {
        
        public PlayerGunner Group;
        
        private PlayerGunner _Event;
        
        private uFrame.ECS.Systems.EcsSystem _System;
        
        private object ActionNode35_message = default( System.Object );
        
        private string StringNode36 = "go go go";
        
        public PlayerGunner Event {
            get {
                return _Event;
            }
            set {
                _Event = value;
            }
        }
        
        public uFrame.ECS.Systems.EcsSystem System {
            get {
                return _System;
            }
            set {
                _System = value;
            }
        }
        
        public virtual System.Collections.IEnumerator Execute() {
            ActionNode35_message = StringNode36;
            // ActionNode
            while (this.DebugInfo("b810e010-5a71-4496-bbd5-842a98b926ba","b2aed14c-b68b-4eaa-86eb-3751d2b59316", this) == 1) yield return null;
            // Visit uFrame.ECS.Actions.DebugLibrary.LogMessage
            uFrame.ECS.Actions.DebugLibrary.LogMessage(ActionNode35_message);
            yield break;
        }
    }
}
