// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace uFrameECSExample {
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;
    using uFrame.ECS;
    using uFrame.ECS.UnityUtilities;
    using uFrame.Kernel;
    using UnityEngine;
    
    
    public class SetScoreLabel {
        
        public WavesGame Group;
        
        public int OldValue;
        
        public int NewValue;
        
        private WavesGame _Event;
        
        private uFrame.ECS.Systems.EcsSystem _System;
        
        private uFrameECSExample.ScoreText LoopGroupNode43_Item = default( uFrameECSExample.ScoreText );
        
        private string FormatStringAction44_Result = default( System.String );
        
        public WavesGame Event {
            get {
                return _Event;
            }
            set {
                _Event = value;
            }
        }
        
        public uFrame.ECS.Systems.EcsSystem System {
            get {
                return _System;
            }
            set {
                _System = value;
            }
        }
        
        public virtual System.Collections.IEnumerator Execute() {
            // LoopGroupNode
            while (this.DebugInfo("c72535ce-34bb-433a-a101-028cf29474a8","a2f6219e-a024-433d-b7da-012d83f704ec", this) == 1) yield return null;
            var LoopGroupNode43_GroupComponents = System.ComponentSystem.RegisterComponent<uFrameECSExample.ScoreText>().Components;
            for (var LoopGroupNode43_ItemIndex = 0
            ; LoopGroupNode43_ItemIndex < LoopGroupNode43_GroupComponents.Count; LoopGroupNode43_ItemIndex++
            ) {
                LoopGroupNode43_Item = LoopGroupNode43_GroupComponents[LoopGroupNode43_ItemIndex];
                System.StartCoroutine(LoopGroupNode43_Next());
            }
            yield break;
        }
        
        private System.Collections.IEnumerator LoopGroupNode43_Next() {
            // FormatStringAction
            while (this.DebugInfo("a2f6219e-a024-433d-b7da-012d83f704ec","dd129801-cadc-4df0-adf1-b2efc24364c5", this) == 1) yield return null;
            FormatStringAction44_Result = string.Format(@"Score: {0}", Group.Score);
            // SetVariableNode
            while (this.DebugInfo("dd129801-cadc-4df0-adf1-b2efc24364c5","ba447786-2d3a-42d4-8e7a-889067259ba2", this) == 1) yield return null;
            LoopGroupNode43_Item.Text.text = (System.String)FormatStringAction44_Result;
            yield break;
        }
    }
}
