// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace uFrameECSExample {
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;
    using uFrame.ECS;
    using uFrame.ECS.UnityUtilities;
    using uFrame.Kernel;
    using UnityEngine;
    
    
    public class ShooterFixedUpdateHandler {
        
        public Movable Group;
        
        private uFrame.ECS.APIs.ISystemFixedUpdate _Event;
        
        private uFrame.ECS.Systems.EcsSystem _System;
        
        private string ActionNode43_axisName = default( System.String );
        
        private string StringNode44 = "Horizontal";
        
        private float ActionNode43_Result = default( System.Single );
        
        private string ActionNode46_axisName = default( System.String );
        
        private string StringNode47 = "Vertical";
        
        private float ActionNode46_Result = default( System.Single );
        
        private UnityEngine.GameObject ActionNode38_go = default( UnityEngine.GameObject );
        
        private UnityEngine.MonoBehaviour ActionNode38_component = default( UnityEngine.MonoBehaviour );
        
        private UnityEngine.Rigidbody ActionNode38_Result = default( UnityEngine.Rigidbody );
        
        private UnityEngine.Rigidbody ActionNode17_rigidBody = default( UnityEngine.Rigidbody );
        
        private float ActionNode17_x = default( System.Single );
        
        private float ActionNode17_y = default( System.Single );
        
        private float ActionNode17_z = default( System.Single );
        
        private float ActionNode17_speed = default( System.Single );
        
        private UnityEngine.Rigidbody ActionNode49_rigidBody = default( UnityEngine.Rigidbody );
        
        private float ActionNode49_x = default( System.Single );
        
        private float ActionNode49_y = default( System.Single );
        
        private float ActionNode40_a = default( System.Single );
        
        private float ActionNode40_b = default( System.Single );
        
        private float ActionNode40_result = default( System.Single );
        
        private float ActionNode49_z = default( System.Single );
        
        public uFrame.ECS.APIs.ISystemFixedUpdate Event {
            get {
                return _Event;
            }
            set {
                _Event = value;
            }
        }
        
        public uFrame.ECS.Systems.EcsSystem System {
            get {
                return _System;
            }
            set {
                _System = value;
            }
        }
        
        public virtual System.Collections.IEnumerator Execute() {
            // ActionGroupNode
            while (this.DebugInfo("c8d77176-13e6-4d8c-ab9d-5862b74f0207","9106a9f9-879b-446d-8c33-030e936d11b2", this) == 1) yield return null;
            ActionNode43_axisName = StringNode44;
            // ActionNode
            while (this.DebugInfo("9106a9f9-879b-446d-8c33-030e936d11b2","c5b8d0d3-50e7-409d-8e68-5abb7462ae26", this) == 1) yield return null;
            // Visit UnityEngine.Input.GetAxis
            ActionNode43_Result = UnityEngine.Input.GetAxis(ActionNode43_axisName);
            // SetVariableNode
            while (this.DebugInfo("c5b8d0d3-50e7-409d-8e68-5abb7462ae26","48c0bd95-a9e4-4447-bf26-3897b4d6f83e", this) == 1) yield return null;
            Group.Horizontal = (System.Single)ActionNode43_Result;
            ActionNode46_axisName = StringNode47;
            // ActionNode
            while (this.DebugInfo("48c0bd95-a9e4-4447-bf26-3897b4d6f83e","7cc0908a-c8e5-426a-9fb0-469d28a76170", this) == 1) yield return null;
            // Visit UnityEngine.Input.GetAxis
            ActionNode46_Result = UnityEngine.Input.GetAxis(ActionNode46_axisName);
            // SetVariableNode
            while (this.DebugInfo("7cc0908a-c8e5-426a-9fb0-469d28a76170","a4629961-e182-414b-bbb0-19daee203747", this) == 1) yield return null;
            Group.Vertical = (System.Single)ActionNode46_Result;
            ActionNode38_go = Group.Entity.gameObject;
            // ActionNode
            while (this.DebugInfo("a4629961-e182-414b-bbb0-19daee203747","6db631f1-896c-48b5-b605-6142eec731ca", this) == 1) yield return null;
            // Visit uFrame.ECS.Actions.UnityLibrary.GetRigidbody
            ActionNode38_Result = uFrame.ECS.Actions.UnityLibrary.GetRigidbody(ActionNode38_go, ActionNode38_component);
            ActionNode17_rigidBody = ActionNode38_Result;
            ActionNode17_x = Group.Horizontal;
            ActionNode17_z = Group.Vertical;
            ActionNode17_speed = Group.Speed;
            // ActionNode
            while (this.DebugInfo("6db631f1-896c-48b5-b605-6142eec731ca","6867565f-f3ec-4f4c-a686-883dad624d1a", this) == 1) yield return null;
            // Visit uFrame.ECS.Actions.RigidbodyLibrary.SetVelocityWithSpeed
            uFrame.ECS.Actions.RigidbodyLibrary.SetVelocityWithSpeed(ActionNode17_rigidBody, ActionNode17_x, ActionNode17_y, ActionNode17_z, ActionNode17_speed);
            ActionNode49_rigidBody = ActionNode38_Result;
            ActionNode40_a = ActionNode38_Result.velocity.x;
            ActionNode40_b = Group.Tilt;
            // ActionNode
            while (this.DebugInfo("6867565f-f3ec-4f4c-a686-883dad624d1a","15c1f8e3-0ce0-4576-aed9-4db12dc2d34d", this) == 1) yield return null;
            // Visit uFrame.ECS.Actions.MathLibrary.Multiply
            uFrame.ECS.Actions.MathLibrary.Multiply(ActionNode40_a, ActionNode40_b, out ActionNode40_result);
            ActionNode49_z = ActionNode40_result;
            // ActionNode
            while (this.DebugInfo("15c1f8e3-0ce0-4576-aed9-4db12dc2d34d","c2f634be-3040-40e8-af07-ccd166b2cb6d", this) == 1) yield return null;
            // Visit uFrame.ECS.Actions.RigidbodyLibrary.SetRigidbodyRotation
            uFrame.ECS.Actions.RigidbodyLibrary.SetRigidbodyRotation(ActionNode49_rigidBody, ActionNode49_x, ActionNode49_y, ActionNode49_z);
            yield break;
        }
    }
}
