// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace Example {
    using Example;
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;
    using uFrame.IOC;
    using uFrame.Kernel;
    using uFrame.Kernel.Serialization;
    using uFrame.MVVM;
    using UnityEngine;
    
    
    public class AssetsLoadingSceneLoaderBase : SceneLoader<AssetsLoadingScene> {
        
        protected override IEnumerator LoadScene(AssetsLoadingScene scene, Action<float, string> progressDelegate) {
            yield break;
        }
        
        protected override IEnumerator UnloadScene(AssetsLoadingScene scene, Action<float, string> progressDelegate) {
            yield break;
        }
    }
    
    public class LevelSceneLoaderBase : SceneLoader<LevelScene> {
        
        protected override IEnumerator LoadScene(LevelScene scene, Action<float, string> progressDelegate) {
            yield break;
        }
        
        protected override IEnumerator UnloadScene(LevelScene scene, Action<float, string> progressDelegate) {
            yield break;
        }
    }
    
    public class MainMenuSceneLoaderBase : SceneLoader<MainMenuScene> {
        
        protected override IEnumerator LoadScene(MainMenuScene scene, Action<float, string> progressDelegate) {
            yield break;
        }
        
        protected override IEnumerator UnloadScene(MainMenuScene scene, Action<float, string> progressDelegate) {
            yield break;
        }
    }
    
    public class IntroSceneLoaderBase : SceneLoader<IntroScene> {
        
        protected override IEnumerator LoadScene(IntroScene scene, Action<float, string> progressDelegate) {
            yield break;
        }
        
        protected override IEnumerator UnloadScene(IntroScene scene, Action<float, string> progressDelegate) {
            yield break;
        }
    }
}
