// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace Example {
    using Example;
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;
    using uFrame.Kernel;
    using uFrame.Kernel.Serialization;
    
    
    public class AssetsLoadingSceneSettingsBase : SceneSettings<AssetsLoadingScene> {
    }
    
    public class LevelSceneSettingsBase : SceneSettings<LevelScene> {
    }
    
    public class MainMenuSceneSettingsBase : SceneSettings<MainMenuScene> {
    }
    
    public class IntroSceneSettingsBase : SceneSettings<IntroScene> {
    }
}
