// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace Example {
    using Example;
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;
    
    
    public class AssetsLoadingSceneBase : uFrame.Kernel.Scene {
        
        public override string DefaultKernelScene {
            get {
                return "ExampleKernelScene";
            }
        }
        
        public virtual AssetsLoadingSceneSettings Settings {
            get {
                return _SettingsObject as AssetsLoadingSceneSettings;
            }
            set {
                _SettingsObject = value;
            }
        }
    }
    
    public class LevelSceneBase : uFrame.Kernel.Scene {
        
        public override string DefaultKernelScene {
            get {
                return "ExampleKernelScene";
            }
        }
        
        public virtual LevelSceneSettings Settings {
            get {
                return _SettingsObject as LevelSceneSettings;
            }
            set {
                _SettingsObject = value;
            }
        }
    }
    
    public class MainMenuSceneBase : uFrame.Kernel.Scene {
        
        public override string DefaultKernelScene {
            get {
                return "ExampleKernelScene";
            }
        }
        
        public virtual MainMenuSceneSettings Settings {
            get {
                return _SettingsObject as MainMenuSceneSettings;
            }
            set {
                _SettingsObject = value;
            }
        }
    }
    
    public class IntroSceneBase : uFrame.Kernel.Scene {
        
        public override string DefaultKernelScene {
            get {
                return "ExampleKernelScene";
            }
        }
        
        public virtual IntroSceneSettings Settings {
            get {
                return _SettingsObject as IntroSceneSettings;
            }
            set {
                _SettingsObject = value;
            }
        }
    }
}
