// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace uFrameECSExample {
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;
    using uFrame.ECS.APIs;
    using uFrame.ECS.Components;
    using uFrame.ECS.Systems;
    using uFrame.Kernel;
    using UniRx;
    
    
    public partial class PlayerGunnerGroup : ReactiveGroup<PlayerGunner> {
        
        private IEcsComponentManagerOf<Gunner> _GunnerManager;
        
        private IEcsComponentManagerOf<GunnerInput> _GunnerInputManager;
        
        private int lastEntityId;
        
        private Gunner Gunner;
        
        private GunnerInput GunnerInput;
        
        public IEcsComponentManagerOf<Gunner> GunnerManager {
            get {
                return _GunnerManager;
            }
            set {
                _GunnerManager = value;
            }
        }
        
        public IEcsComponentManagerOf<GunnerInput> GunnerInputManager {
            get {
                return _GunnerInputManager;
            }
            set {
                _GunnerInputManager = value;
            }
        }
        
        public override System.Collections.Generic.IEnumerable<UniRx.IObservable<int>> Install(uFrame.ECS.APIs.IComponentSystem componentSystem) {
            GunnerManager = componentSystem.RegisterComponent<Gunner>();
            yield return GunnerManager.CreatedObservable.Select(_=>_.EntityId);;
            yield return GunnerManager.RemovedObservable.Select(_=>_.EntityId);;
            GunnerInputManager = componentSystem.RegisterComponent<GunnerInput>();
            yield return GunnerInputManager.CreatedObservable.Select(_=>_.EntityId);;
            yield return GunnerInputManager.RemovedObservable.Select(_=>_.EntityId);;
        }
        
        public override bool Match(int entityId) {
            lastEntityId = entityId;
            if ((Gunner = GunnerManager[entityId]) == null) {
                return false;
            }
            if ((GunnerInput = GunnerInputManager[entityId]) == null) {
                return false;
            }
            return true;
        }
        
        public override PlayerGunner Select() {
            var item = new PlayerGunner();;
            item.EntityId = lastEntityId;
            item.Gunner = Gunner;
            item.GunnerInput = GunnerInput;
            return item;
        }
    }
}
