// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

using uFrame.Editor.Documentation;

namespace uFrame.ECS.Editor
{
    public class uFrameECSDocumentationProviderBase : DocumentationDefaultProvider {
        
        public override void GetPages(System.Collections.Generic.List<DocumentationPage> rootPages) {
            base.GetPages(rootPages);
        }
    }
}
