// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace uFrame.ECS.Editor {
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;
    using uFrame.Editor.GraphUI.Drawers;
    
    
    public class CustomActionNodeDrawerBase : GenericNodeDrawer<CustomActionNode,CustomActionNodeViewModel> {
        
        public CustomActionNodeDrawerBase(CustomActionNodeViewModel viewModel) : 
                base(viewModel) {
        }
    }
    
    public class DataNodeDrawerBase : GenericNodeDrawer<DataNode,DataNodeViewModel> {
        
        public DataNodeDrawerBase(DataNodeViewModel viewModel) : 
                base(viewModel) {
        }
    }
    
    public class LibraryNodeDrawerBase : GenericNodeDrawer<LibraryNode,LibraryNodeViewModel> {
        
        public LibraryNodeDrawerBase(LibraryNodeViewModel viewModel) : 
                base(viewModel) {
        }
    }
    
    public class NullNodeDrawerBase : GenericNodeDrawer<NullNode,NullNodeViewModel> {
        
        public NullNodeDrawerBase(NullNodeViewModel viewModel) : 
                base(viewModel) {
        }
    }
    
    public class StringLiteralNodeDrawerBase : GenericNodeDrawer<StringLiteralNode,StringLiteralNodeViewModel> {
        
        public StringLiteralNodeDrawerBase(StringLiteralNodeViewModel viewModel) : 
                base(viewModel) {
        }
    }
    
    public class PropertyNodeDrawerBase : GenericNodeDrawer<PropertyNode,PropertyNodeViewModel> {
        
        public PropertyNodeDrawerBase(PropertyNodeViewModel viewModel) : 
                base(viewModel) {
        }
    }
    
    public class StringNodeDrawerBase : GenericNodeDrawer<StringNode,StringNodeViewModel> {
        
        public StringNodeDrawerBase(StringNodeViewModel viewModel) : 
                base(viewModel) {
        }
    }
    
    public class ActionGroupNodeDrawerBase : GenericNodeDrawer<ActionGroupNode,ActionGroupNodeViewModel> {
        
        public ActionGroupNodeDrawerBase(ActionGroupNodeViewModel viewModel) : 
                base(viewModel) {
        }
    }
    
    public class FunctionNodeDrawerBase : GenericNodeDrawer<FunctionNode,FunctionNodeViewModel> {
        
        public FunctionNodeDrawerBase(FunctionNodeViewModel viewModel) : 
                base(viewModel) {
        }
    }
    
    public class BoolNodeDrawerBase : GenericNodeDrawer<BoolNode,BoolNodeViewModel> {
        
        public BoolNodeDrawerBase(BoolNodeViewModel viewModel) : 
                base(viewModel) {
        }
    }
    
    public class ModuleNodeDrawerBase : GenericNodeDrawer<ModuleNode,ModuleNodeViewModel> {
        
        public ModuleNodeDrawerBase(ModuleNodeViewModel viewModel) : 
                base(viewModel) {
        }
    }
    
    public class AnyFalseNodeDrawerBase : GenericNodeDrawer<AnyFalseNode,AnyFalseNodeViewModel> {
        
        public AnyFalseNodeDrawerBase(AnyFalseNodeViewModel viewModel) : 
                base(viewModel) {
        }
    }
    
    public class CodeActionNodeDrawerBase : GenericNodeDrawer<CodeActionNode,CodeActionNodeViewModel> {
        
        public CodeActionNodeDrawerBase(CodeActionNodeViewModel viewModel) : 
                base(viewModel) {
        }
    }
    
    public class BoolExpressionNodeDrawerBase : GenericNodeDrawer<BoolExpressionNode,BoolExpressionNodeViewModel> {
        
        public BoolExpressionNodeDrawerBase(BoolExpressionNodeViewModel viewModel) : 
                base(viewModel) {
        }
    }
    
    public class FloatNodeDrawerBase : GenericNodeDrawer<FloatNode,FloatNodeViewModel> {
        
        public FloatNodeDrawerBase(FloatNodeViewModel viewModel) : 
                base(viewModel) {
        }
    }
    
    public class UserMethodNodeDrawerBase : GenericNodeDrawer<UserMethodNode,UserMethodNodeViewModel> {
        
        public UserMethodNodeDrawerBase(UserMethodNodeViewModel viewModel) : 
                base(viewModel) {
        }
    }
    
    public class LoopCollectionNodeDrawerBase : GenericNodeDrawer<LoopCollectionNode,LoopCollectionNodeViewModel> {
        
        public LoopCollectionNodeDrawerBase(LoopCollectionNodeViewModel viewModel) : 
                base(viewModel) {
        }
    }
    
    public class ComponentCreatedNodeDrawerBase : GenericNodeDrawer<ComponentCreatedNode,ComponentCreatedNodeViewModel> {
        
        public ComponentCreatedNodeDrawerBase(ComponentCreatedNodeViewModel viewModel) : 
                base(viewModel) {
        }
    }
    
    public class SetVariableNodeDrawerBase : GenericNodeDrawer<SetVariableNode,SetVariableNodeViewModel> {
        
        public SetVariableNodeDrawerBase(SetVariableNodeViewModel viewModel) : 
                base(viewModel) {
        }
    }
    
    public class AnyTrueNodeDrawerBase : GenericNodeDrawer<AnyTrueNode,AnyTrueNodeViewModel> {
        
        public AnyTrueNodeDrawerBase(AnyTrueNodeViewModel viewModel) : 
                base(viewModel) {
        }
    }
    
    public class CollectionItemRemovedNodeDrawerBase : GenericNodeDrawer<CollectionItemRemovedNode,CollectionItemRemovedNodeViewModel> {
        
        public CollectionItemRemovedNodeDrawerBase(CollectionItemRemovedNodeViewModel viewModel) : 
                base(viewModel) {
        }
    }
    
    public class CollectionModifiedHandlerNodeDrawerBase : GenericNodeDrawer<CollectionModifiedHandlerNode,CollectionModifiedHandlerNodeViewModel> {
        
        public CollectionModifiedHandlerNodeDrawerBase(CollectionModifiedHandlerNodeViewModel viewModel) : 
                base(viewModel) {
        }
    }
    
    public class ObjectNodeDrawerBase : GenericNodeDrawer<ObjectNode,ObjectNodeViewModel> {
        
        public ObjectNodeDrawerBase(ObjectNodeViewModel viewModel) : 
                base(viewModel) {
        }
    }
    
    public class PropertyChangedNodeDrawerBase : GenericNodeDrawer<PropertyChangedNode,PropertyChangedNodeViewModel> {
        
        public PropertyChangedNodeDrawerBase(PropertyChangedNodeViewModel viewModel) : 
                base(viewModel) {
        }
    }
    
    public class VariableNodeDrawerBase : GenericNodeDrawer<VariableNode,VariableNodeViewModel> {
        
        public VariableNodeDrawerBase(VariableNodeViewModel viewModel) : 
                base(viewModel) {
        }
    }
    
    public class GroupNodeDrawerBase : GenericNodeDrawer<GroupNode,GroupNodeViewModel> {
        
        public GroupNodeDrawerBase(GroupNodeViewModel viewModel) : 
                base(viewModel) {
        }
    }
    
    public class DescriptorNodeDrawerBase : GenericNodeDrawer<DescriptorNode,DescriptorNodeViewModel> {
        
        public DescriptorNodeDrawerBase(DescriptorNodeViewModel viewModel) : 
                base(viewModel) {
        }
    }
    
    public class Vector3NodeDrawerBase : GenericNodeDrawer<Vector3Node,Vector3NodeViewModel> {
        
        public Vector3NodeDrawerBase(Vector3NodeViewModel viewModel) : 
                base(viewModel) {
        }
    }
    
    public class EventNodeDrawerBase : GenericNodeDrawer<EventNode,EventNodeViewModel> {
        
        public EventNodeDrawerBase(EventNodeViewModel viewModel) : 
                base(viewModel) {
        }
    }
    
    public class LiteralNodeDrawerBase : GenericNodeDrawer<LiteralNode,LiteralNodeViewModel> {
        
        public LiteralNodeDrawerBase(LiteralNodeViewModel viewModel) : 
                base(viewModel) {
        }
    }
    
    public class ComponentNodeDrawerBase : GenericNodeDrawer<ComponentNode,ComponentNodeViewModel> {
        
        public ComponentNodeDrawerBase(ComponentNodeViewModel viewModel) : 
                base(viewModel) {
        }
    }
    
    public class AllFalseNodeDrawerBase : GenericNodeDrawer<AllFalseNode,AllFalseNodeViewModel> {
        
        public AllFalseNodeDrawerBase(AllFalseNodeViewModel viewModel) : 
                base(viewModel) {
        }
    }
    
    public class IntNodeDrawerBase : GenericNodeDrawer<IntNode,IntNodeViewModel> {
        
        public IntNodeDrawerBase(IntNodeViewModel viewModel) : 
                base(viewModel) {
        }
    }
    
    public class CollectionItemAddedNodeDrawerBase : GenericNodeDrawer<CollectionItemAddedNode,CollectionItemAddedNodeViewModel> {
        
        public CollectionItemAddedNodeDrawerBase(CollectionItemAddedNodeViewModel viewModel) : 
                base(viewModel) {
        }
    }
    
    public class ComponentDestroyedNodeDrawerBase : GenericNodeDrawer<ComponentDestroyedNode,ComponentDestroyedNodeViewModel> {
        
        public ComponentDestroyedNodeDrawerBase(ComponentDestroyedNodeViewModel viewModel) : 
                base(viewModel) {
        }
    }
    
    public class Vector2NodeDrawerBase : GenericNodeDrawer<Vector2Node,Vector2NodeViewModel> {
        
        public Vector2NodeDrawerBase(Vector2NodeViewModel viewModel) : 
                base(viewModel) {
        }
    }
    
    public class SequenceContainerNodeDrawerBase : GenericNodeDrawer<SequenceContainerNode,SequenceContainerNodeViewModel> {
        
        public SequenceContainerNodeDrawerBase(SequenceContainerNodeViewModel viewModel) : 
                base(viewModel) {
        }
    }
    
    public class AllTrueNodeDrawerBase : GenericNodeDrawer<AllTrueNode,AllTrueNodeViewModel> {
        
        public AllTrueNodeDrawerBase(AllTrueNodeViewModel viewModel) : 
                base(viewModel) {
        }
    }
    
    public class StopTimerNodeDrawerBase : GenericNodeDrawer<StopTimerNode,StopTimerNodeViewModel> {
        
        public StopTimerNodeDrawerBase(StopTimerNodeViewModel viewModel) : 
                base(viewModel) {
        }
    }
    
    public class StartTimerNodeDrawerBase : GenericNodeDrawer<StartTimerNode,StartTimerNodeViewModel> {
        
        public StartTimerNodeDrawerBase(StartTimerNodeViewModel viewModel) : 
                base(viewModel) {
        }
    }
    
    public class ConditionNodeDrawerBase : GenericNodeDrawer<ConditionNode,ConditionNodeViewModel> {
        
        public ConditionNodeDrawerBase(ConditionNodeViewModel viewModel) : 
                base(viewModel) {
        }
    }
    
    public class ActionNodeDrawerBase : GenericNodeDrawer<ActionNode,ActionNodeViewModel> {
        
        public ActionNodeDrawerBase(ActionNodeViewModel viewModel) : 
                base(viewModel) {
        }
    }
    
    public class HandlerNodeDrawerBase : GenericNodeDrawer<HandlerNode,HandlerNodeViewModel> {
        
        public HandlerNodeDrawerBase(HandlerNodeViewModel viewModel) : 
                base(viewModel) {
        }
    }
    
    public class SystemNodeDrawerBase : GenericNodeDrawer<SystemNode,SystemNodeViewModel> {
        
        public SystemNodeDrawerBase(SystemNodeViewModel viewModel) : 
                base(viewModel) {
        }
    }
    
    public class EntityNodeDrawerBase : GenericNodeDrawer<EntityNode,EntityNodeViewModel> {
        
        public EntityNodeDrawerBase(EntityNodeViewModel viewModel) : 
                base(viewModel) {
        }
    }
    
    public class ColorNodeDrawerBase : GenericNodeDrawer<ColorNode,ColorNodeViewModel> {
        
        public ColorNodeDrawerBase(ColorNodeViewModel viewModel) : 
                base(viewModel) {
        }
    }
    
    public class EnumValueNodeDrawerBase : GenericNodeDrawer<EnumValueNode,EnumValueNodeViewModel> {
        
        public EnumValueNodeDrawerBase(EnumValueNodeViewModel viewModel) : 
                base(viewModel) {
        }
    }
    
    public class SequenceItemNodeDrawerBase : GenericNodeDrawer<SequenceItemNode,SequenceItemNodeViewModel> {
        
        public SequenceItemNodeDrawerBase(SequenceItemNodeViewModel viewModel) : 
                base(viewModel) {
        }
    }
}
