// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace uFrame.ECS.Editor {
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;
    using uFrame.Editor.Database.Data;
    using uFrame.Editor.Graphs.Data;
    
    
    public class TimerBase : SingleInputSlot<ITimerConnectable> {
        
        public override string Name {
            get {
                return "Timer";
            }
            set {
            }
        }
        
        public override bool AllowMultipleInputs {
            get {
                return false;
            }
        }
        
        public override bool AllowMultipleOutputs {
            get {
                return false;
            }
        }
        
        public override bool AllowSelection {
            get {
                return false;
            }
        }
        
        public override System.Collections.Generic.IEnumerable<uFrame.Editor.Database.Data.IValueItem> GetAllowed() {
            return Repository.AllOf<ITimerConnectable>().OfType<IValueItem>();;
        }
    }
    
    public partial interface ITimerConnectable : uFrame.Editor.Graphs.Data.IDiagramNodeItem, uFrame.Editor.Graphs.Data.IConnectable {
    }
    
    public class ExpressionsBase : MultiInputSlot<IExpressionsConnectable> {
        
        public override string Name {
            get {
                return "Expressions";
            }
            set {
            }
        }
        
        public override bool AllowMultipleInputs {
            get {
                return true;
            }
        }
        
        public override bool AllowMultipleOutputs {
            get {
                return false;
            }
        }
        
        public override bool AllowSelection {
            get {
                return false;
            }
        }
        
        public override System.Collections.Generic.IEnumerable<uFrame.Editor.Database.Data.IValueItem> GetAllowed() {
            return Repository.AllOf<IExpressionsConnectable>().OfType<IValueItem>();;
        }
    }
    
    public partial interface IExpressionsConnectable : uFrame.Editor.Graphs.Data.IDiagramNodeItem, uFrame.Editor.Graphs.Data.IConnectable {
    }
}
