// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace uFrame.ECS.Editor {
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;
    using uFrame.Editor.Graphs.Data;
    using uFrame.Editor.GraphUI.ViewModels;
    using uFrame.Editor.Platform;
    
    
    public class CustomActionNodeViewModelBase : SequenceContainerNodeViewModel {
        
        public CustomActionNodeViewModelBase(CustomActionNode graphItemObject, uFrame.Editor.GraphUI.ViewModels.DiagramViewModel diagramViewModel) : 
                base(graphItemObject, diagramViewModel) {
        }
        
        public override uFrame.Editor.Platform.NodeStyle NodeStyle {
            get {
                return NodeStyle.Normal;
            }
        }
    }
    
    public class DataNodeViewModelBase : uFrame.Editor.GraphUI.ViewModels.GenericNodeViewModel<uFrame.Editor.Graphs.Data.GenericNode> {
        
        public DataNodeViewModelBase(DataNode graphItemObject, uFrame.Editor.GraphUI.ViewModels.DiagramViewModel diagramViewModel) : 
                base(graphItemObject, diagramViewModel) {
        }
        
        public override uFrame.Editor.Platform.NodeStyle NodeStyle {
            get {
                return NodeStyle.Normal;
            }
        }
    }
    
    public class LibraryNodeViewModelBase : uFrame.Editor.GraphUI.ViewModels.GenericNodeViewModel<uFrame.Editor.Graphs.Data.GenericNode> {
        
        public LibraryNodeViewModelBase(LibraryNode graphItemObject, uFrame.Editor.GraphUI.ViewModels.DiagramViewModel diagramViewModel) : 
                base(graphItemObject, diagramViewModel) {
        }
        
        public override uFrame.Editor.Platform.NodeStyle NodeStyle {
            get {
                return NodeStyle.Normal;
            }
        }
    }
    
    public class NullNodeViewModelBase : LiteralNodeViewModel {
        
        public NullNodeViewModelBase(NullNode graphItemObject, uFrame.Editor.GraphUI.ViewModels.DiagramViewModel diagramViewModel) : 
                base(graphItemObject, diagramViewModel) {
        }
        
        public override uFrame.Editor.Platform.NodeStyle NodeStyle {
            get {
                return NodeStyle.Normal;
            }
        }
    }
    
    public class StringLiteralNodeViewModelBase : VariableNodeViewModel {
        
        public StringLiteralNodeViewModelBase(StringLiteralNode graphItemObject, uFrame.Editor.GraphUI.ViewModels.DiagramViewModel diagramViewModel) : 
                base(graphItemObject, diagramViewModel) {
        }
        
        public override uFrame.Editor.Platform.NodeStyle NodeStyle {
            get {
                return NodeStyle.Normal;
            }
        }
    }
    
    public class PropertyNodeViewModelBase : uFrame.Editor.GraphUI.ViewModels.GenericNodeViewModel<uFrame.Editor.Graphs.Data.GenericNode> {
        
        public PropertyNodeViewModelBase(PropertyNode graphItemObject, uFrame.Editor.GraphUI.ViewModels.DiagramViewModel diagramViewModel) : 
                base(graphItemObject, diagramViewModel) {
        }
        
        public override uFrame.Editor.Platform.NodeStyle NodeStyle {
            get {
                return NodeStyle.Minimalistic;
            }
        }
    }
    
    public class StringNodeViewModelBase : LiteralNodeViewModel {
        
        public StringNodeViewModelBase(StringNode graphItemObject, uFrame.Editor.GraphUI.ViewModels.DiagramViewModel diagramViewModel) : 
                base(graphItemObject, diagramViewModel) {
        }
        
        public override uFrame.Editor.Platform.NodeStyle NodeStyle {
            get {
                return NodeStyle.Minimalistic;
            }
        }
    }
    
    public class ActionGroupNodeViewModelBase : SequenceItemNodeViewModel {
        
        public ActionGroupNodeViewModelBase(ActionGroupNode graphItemObject, uFrame.Editor.GraphUI.ViewModels.DiagramViewModel diagramViewModel) : 
                base(graphItemObject, diagramViewModel) {
        }
        
        public override uFrame.Editor.Platform.NodeStyle NodeStyle {
            get {
                return NodeStyle.Normal;
            }
        }
    }
    
    public class FunctionNodeViewModelBase : SequenceItemNodeViewModel {
        
        public FunctionNodeViewModelBase(FunctionNode graphItemObject, uFrame.Editor.GraphUI.ViewModels.DiagramViewModel diagramViewModel) : 
                base(graphItemObject, diagramViewModel) {
        }
        
        public override uFrame.Editor.Platform.NodeStyle NodeStyle {
            get {
                return NodeStyle.Normal;
            }
        }
    }
    
    public class BoolNodeViewModelBase : LiteralNodeViewModel {
        
        public BoolNodeViewModelBase(BoolNode graphItemObject, uFrame.Editor.GraphUI.ViewModels.DiagramViewModel diagramViewModel) : 
                base(graphItemObject, diagramViewModel) {
        }
        
        public override uFrame.Editor.Platform.NodeStyle NodeStyle {
            get {
                return NodeStyle.Minimalistic;
            }
        }
    }
    
    public class ModuleNodeViewModelBase : uFrame.Editor.GraphUI.ViewModels.GenericNodeViewModel<uFrame.Editor.Graphs.Data.GenericNode> {
        
        public ModuleNodeViewModelBase(ModuleNode graphItemObject, uFrame.Editor.GraphUI.ViewModels.DiagramViewModel diagramViewModel) : 
                base(graphItemObject, diagramViewModel) {
        }
        
        public override uFrame.Editor.Platform.NodeStyle NodeStyle {
            get {
                return NodeStyle.Normal;
            }
        }
    }
    
    public class AnyFalseNodeViewModelBase : BoolExpressionNodeViewModel {
        
        public AnyFalseNodeViewModelBase(AnyFalseNode graphItemObject, uFrame.Editor.GraphUI.ViewModels.DiagramViewModel diagramViewModel) : 
                base(graphItemObject, diagramViewModel) {
        }
        
        public override uFrame.Editor.Platform.NodeStyle NodeStyle {
            get {
                return NodeStyle.Minimalistic;
            }
        }
    }
    
    public class CodeActionNodeViewModelBase : ActionNodeViewModel {
        
        public CodeActionNodeViewModelBase(CodeActionNode graphItemObject, uFrame.Editor.GraphUI.ViewModels.DiagramViewModel diagramViewModel) : 
                base(graphItemObject, diagramViewModel) {
        }
        
        public override uFrame.Editor.Platform.NodeStyle NodeStyle {
            get {
                return NodeStyle.Normal;
            }
        }
    }
    
    public class BoolExpressionNodeViewModelBase : uFrame.Editor.GraphUI.ViewModels.GenericNodeViewModel<uFrame.Editor.Graphs.Data.GenericNode> {
        
        public BoolExpressionNodeViewModelBase(BoolExpressionNode graphItemObject, uFrame.Editor.GraphUI.ViewModels.DiagramViewModel diagramViewModel) : 
                base(graphItemObject, diagramViewModel) {
        }
        
        public override uFrame.Editor.Platform.NodeStyle NodeStyle {
            get {
                return NodeStyle.Normal;
            }
        }
    }
    
    public class FloatNodeViewModelBase : LiteralNodeViewModel {
        
        public FloatNodeViewModelBase(FloatNode graphItemObject, uFrame.Editor.GraphUI.ViewModels.DiagramViewModel diagramViewModel) : 
                base(graphItemObject, diagramViewModel) {
        }
        
        public override uFrame.Editor.Platform.NodeStyle NodeStyle {
            get {
                return NodeStyle.Minimalistic;
            }
        }
    }
    
    public class UserMethodNodeViewModelBase : SequenceItemNodeViewModel {
        
        public UserMethodNodeViewModelBase(UserMethodNode graphItemObject, uFrame.Editor.GraphUI.ViewModels.DiagramViewModel diagramViewModel) : 
                base(graphItemObject, diagramViewModel) {
        }
        
        public override uFrame.Editor.Platform.NodeStyle NodeStyle {
            get {
                return NodeStyle.Normal;
            }
        }
    }
    
    public class LoopCollectionNodeViewModelBase : SequenceItemNodeViewModel {
        
        public LoopCollectionNodeViewModelBase(LoopCollectionNode graphItemObject, uFrame.Editor.GraphUI.ViewModels.DiagramViewModel diagramViewModel) : 
                base(graphItemObject, diagramViewModel) {
        }
        
        public override uFrame.Editor.Platform.NodeStyle NodeStyle {
            get {
                return NodeStyle.Minimalistic;
            }
        }
    }
    
    public class ComponentCreatedNodeViewModelBase : HandlerNodeViewModel {
        
        public ComponentCreatedNodeViewModelBase(ComponentCreatedNode graphItemObject, uFrame.Editor.GraphUI.ViewModels.DiagramViewModel diagramViewModel) : 
                base(graphItemObject, diagramViewModel) {
        }
        
        public override uFrame.Editor.Platform.NodeStyle NodeStyle {
            get {
                return NodeStyle.Minimalistic;
            }
        }
    }
    
    public class SetVariableNodeViewModelBase : SequenceItemNodeViewModel {
        
        public SetVariableNodeViewModelBase(SetVariableNode graphItemObject, uFrame.Editor.GraphUI.ViewModels.DiagramViewModel diagramViewModel) : 
                base(graphItemObject, diagramViewModel) {
        }
        
        public override uFrame.Editor.Platform.NodeStyle NodeStyle {
            get {
                return NodeStyle.Minimalistic;
            }
        }
    }
    
    public class AnyTrueNodeViewModelBase : BoolExpressionNodeViewModel {
        
        public AnyTrueNodeViewModelBase(AnyTrueNode graphItemObject, uFrame.Editor.GraphUI.ViewModels.DiagramViewModel diagramViewModel) : 
                base(graphItemObject, diagramViewModel) {
        }
        
        public override uFrame.Editor.Platform.NodeStyle NodeStyle {
            get {
                return NodeStyle.Minimalistic;
            }
        }
    }
    
    public class CollectionItemRemovedNodeViewModelBase : CollectionModifiedHandlerNodeViewModel {
        
        public CollectionItemRemovedNodeViewModelBase(CollectionItemRemovedNode graphItemObject, uFrame.Editor.GraphUI.ViewModels.DiagramViewModel diagramViewModel) : 
                base(graphItemObject, diagramViewModel) {
        }
        
        public override uFrame.Editor.Platform.NodeStyle NodeStyle {
            get {
                return NodeStyle.Minimalistic;
            }
        }
    }
    
    public class CollectionModifiedHandlerNodeViewModelBase : HandlerNodeViewModel {
        
        public CollectionModifiedHandlerNodeViewModelBase(CollectionModifiedHandlerNode graphItemObject, uFrame.Editor.GraphUI.ViewModels.DiagramViewModel diagramViewModel) : 
                base(graphItemObject, diagramViewModel) {
        }
        
        public override uFrame.Editor.Platform.NodeStyle NodeStyle {
            get {
                return NodeStyle.Normal;
            }
        }
    }
    
    public class ObjectNodeViewModelBase : LiteralNodeViewModel {
        
        public ObjectNodeViewModelBase(ObjectNode graphItemObject, uFrame.Editor.GraphUI.ViewModels.DiagramViewModel diagramViewModel) : 
                base(graphItemObject, diagramViewModel) {
        }
        
        public override uFrame.Editor.Platform.NodeStyle NodeStyle {
            get {
                return NodeStyle.Normal;
            }
        }
    }
    
    public class PropertyChangedNodeViewModelBase : HandlerNodeViewModel {
        
        public PropertyChangedNodeViewModelBase(PropertyChangedNode graphItemObject, uFrame.Editor.GraphUI.ViewModels.DiagramViewModel diagramViewModel) : 
                base(graphItemObject, diagramViewModel) {
        }
        
        public override uFrame.Editor.Platform.NodeStyle NodeStyle {
            get {
                return NodeStyle.Minimalistic;
            }
        }
    }
    
    public class VariableNodeViewModelBase : uFrame.Editor.GraphUI.ViewModels.GenericNodeViewModel<uFrame.Editor.Graphs.Data.GenericNode> {
        
        public VariableNodeViewModelBase(VariableNode graphItemObject, uFrame.Editor.GraphUI.ViewModels.DiagramViewModel diagramViewModel) : 
                base(graphItemObject, diagramViewModel) {
        }
        
        public override uFrame.Editor.Platform.NodeStyle NodeStyle {
            get {
                return NodeStyle.Normal;
            }
        }
    }
    
    public class GroupNodeViewModelBase : uFrame.Editor.GraphUI.ViewModels.GenericNodeViewModel<uFrame.Editor.Graphs.Data.GenericNode> {
        
        public GroupNodeViewModelBase(GroupNode graphItemObject, uFrame.Editor.GraphUI.ViewModels.DiagramViewModel diagramViewModel) : 
                base(graphItemObject, diagramViewModel) {
        }
        
        public override uFrame.Editor.Platform.NodeStyle NodeStyle {
            get {
                return NodeStyle.Normal;
            }
        }
    }
    
    public class DescriptorNodeViewModelBase : uFrame.Editor.GraphUI.ViewModels.GenericNodeViewModel<uFrame.Editor.Graphs.Data.GenericNode> {
        
        public DescriptorNodeViewModelBase(DescriptorNode graphItemObject, uFrame.Editor.GraphUI.ViewModels.DiagramViewModel diagramViewModel) : 
                base(graphItemObject, diagramViewModel) {
        }
        
        public override uFrame.Editor.Platform.NodeStyle NodeStyle {
            get {
                return NodeStyle.Normal;
            }
        }
    }
    
    public class Vector3NodeViewModelBase : LiteralNodeViewModel {
        
        public Vector3NodeViewModelBase(Vector3Node graphItemObject, uFrame.Editor.GraphUI.ViewModels.DiagramViewModel diagramViewModel) : 
                base(graphItemObject, diagramViewModel) {
        }
        
        public override uFrame.Editor.Platform.NodeStyle NodeStyle {
            get {
                return NodeStyle.Minimalistic;
            }
        }
    }
    
    public class EventNodeViewModelBase : uFrame.Editor.GraphUI.ViewModels.GenericNodeViewModel<uFrame.Editor.Graphs.Data.GenericNode> {
        
        public EventNodeViewModelBase(EventNode graphItemObject, uFrame.Editor.GraphUI.ViewModels.DiagramViewModel diagramViewModel) : 
                base(graphItemObject, diagramViewModel) {
        }
        
        public override uFrame.Editor.Platform.NodeStyle NodeStyle {
            get {
                return NodeStyle.Normal;
            }
        }
    }
    
    public class LiteralNodeViewModelBase : VariableNodeViewModel {
        
        public LiteralNodeViewModelBase(LiteralNode graphItemObject, uFrame.Editor.GraphUI.ViewModels.DiagramViewModel diagramViewModel) : 
                base(graphItemObject, diagramViewModel) {
        }
        
        public override uFrame.Editor.Platform.NodeStyle NodeStyle {
            get {
                return NodeStyle.Minimalistic;
            }
        }
    }
    
    public class ComponentNodeViewModelBase : uFrame.Editor.GraphUI.ViewModels.GenericNodeViewModel<uFrame.Editor.Graphs.Data.GenericNode> {
        
        public ComponentNodeViewModelBase(ComponentNode graphItemObject, uFrame.Editor.GraphUI.ViewModels.DiagramViewModel diagramViewModel) : 
                base(graphItemObject, diagramViewModel) {
        }
        
        public override uFrame.Editor.Platform.NodeStyle NodeStyle {
            get {
                return NodeStyle.Normal;
            }
        }
    }
    
    public class AllFalseNodeViewModelBase : BoolExpressionNodeViewModel {
        
        public AllFalseNodeViewModelBase(AllFalseNode graphItemObject, uFrame.Editor.GraphUI.ViewModels.DiagramViewModel diagramViewModel) : 
                base(graphItemObject, diagramViewModel) {
        }
        
        public override uFrame.Editor.Platform.NodeStyle NodeStyle {
            get {
                return NodeStyle.Minimalistic;
            }
        }
    }
    
    public class IntNodeViewModelBase : LiteralNodeViewModel {
        
        public IntNodeViewModelBase(IntNode graphItemObject, uFrame.Editor.GraphUI.ViewModels.DiagramViewModel diagramViewModel) : 
                base(graphItemObject, diagramViewModel) {
        }
        
        public override uFrame.Editor.Platform.NodeStyle NodeStyle {
            get {
                return NodeStyle.Minimalistic;
            }
        }
    }
    
    public class CollectionItemAddedNodeViewModelBase : CollectionModifiedHandlerNodeViewModel {
        
        public CollectionItemAddedNodeViewModelBase(CollectionItemAddedNode graphItemObject, uFrame.Editor.GraphUI.ViewModels.DiagramViewModel diagramViewModel) : 
                base(graphItemObject, diagramViewModel) {
        }
        
        public override uFrame.Editor.Platform.NodeStyle NodeStyle {
            get {
                return NodeStyle.Minimalistic;
            }
        }
    }
    
    public class ComponentDestroyedNodeViewModelBase : HandlerNodeViewModel {
        
        public ComponentDestroyedNodeViewModelBase(ComponentDestroyedNode graphItemObject, uFrame.Editor.GraphUI.ViewModels.DiagramViewModel diagramViewModel) : 
                base(graphItemObject, diagramViewModel) {
        }
        
        public override uFrame.Editor.Platform.NodeStyle NodeStyle {
            get {
                return NodeStyle.Minimalistic;
            }
        }
    }
    
    public class Vector2NodeViewModelBase : LiteralNodeViewModel {
        
        public Vector2NodeViewModelBase(Vector2Node graphItemObject, uFrame.Editor.GraphUI.ViewModels.DiagramViewModel diagramViewModel) : 
                base(graphItemObject, diagramViewModel) {
        }
        
        public override uFrame.Editor.Platform.NodeStyle NodeStyle {
            get {
                return NodeStyle.Minimalistic;
            }
        }
    }
    
    public class SequenceContainerNodeViewModelBase : SequenceItemNodeViewModel {
        
        public SequenceContainerNodeViewModelBase(SequenceContainerNode graphItemObject, uFrame.Editor.GraphUI.ViewModels.DiagramViewModel diagramViewModel) : 
                base(graphItemObject, diagramViewModel) {
        }
        
        public override uFrame.Editor.Platform.NodeStyle NodeStyle {
            get {
                return NodeStyle.Normal;
            }
        }
    }
    
    public class AllTrueNodeViewModelBase : BoolExpressionNodeViewModel {
        
        public AllTrueNodeViewModelBase(AllTrueNode graphItemObject, uFrame.Editor.GraphUI.ViewModels.DiagramViewModel diagramViewModel) : 
                base(graphItemObject, diagramViewModel) {
        }
        
        public override uFrame.Editor.Platform.NodeStyle NodeStyle {
            get {
                return NodeStyle.Minimalistic;
            }
        }
    }
    
    public class StopTimerNodeViewModelBase : uFrame.Editor.GraphUI.ViewModels.GenericNodeViewModel<uFrame.Editor.Graphs.Data.GenericNode> {
        
        public StopTimerNodeViewModelBase(StopTimerNode graphItemObject, uFrame.Editor.GraphUI.ViewModels.DiagramViewModel diagramViewModel) : 
                base(graphItemObject, diagramViewModel) {
        }
        
        public override uFrame.Editor.Platform.NodeStyle NodeStyle {
            get {
                return NodeStyle.Normal;
            }
        }
    }
    
    public class StartTimerNodeViewModelBase : uFrame.Editor.GraphUI.ViewModels.GenericNodeViewModel<uFrame.Editor.Graphs.Data.GenericNode> {
        
        public StartTimerNodeViewModelBase(StartTimerNode graphItemObject, uFrame.Editor.GraphUI.ViewModels.DiagramViewModel diagramViewModel) : 
                base(graphItemObject, diagramViewModel) {
        }
        
        public override uFrame.Editor.Platform.NodeStyle NodeStyle {
            get {
                return NodeStyle.Normal;
            }
        }
    }
    
    public class ConditionNodeViewModelBase : BoolExpressionNodeViewModel {
        
        public ConditionNodeViewModelBase(ConditionNode graphItemObject, uFrame.Editor.GraphUI.ViewModels.DiagramViewModel diagramViewModel) : 
                base(graphItemObject, diagramViewModel) {
        }
        
        public override uFrame.Editor.Platform.NodeStyle NodeStyle {
            get {
                return NodeStyle.Minimalistic;
            }
        }
    }
    
    public class ActionNodeViewModelBase : SequenceItemNodeViewModel {
        
        public ActionNodeViewModelBase(ActionNode graphItemObject, uFrame.Editor.GraphUI.ViewModels.DiagramViewModel diagramViewModel) : 
                base(graphItemObject, diagramViewModel) {
        }
        
        public override uFrame.Editor.Platform.NodeStyle NodeStyle {
            get {
                return NodeStyle.Minimalistic;
            }
        }
    }
    
    public class HandlerNodeViewModelBase : SequenceContainerNodeViewModel {
        
        public HandlerNodeViewModelBase(HandlerNode graphItemObject, uFrame.Editor.GraphUI.ViewModels.DiagramViewModel diagramViewModel) : 
                base(graphItemObject, diagramViewModel) {
        }
        
        public override uFrame.Editor.Platform.NodeStyle NodeStyle {
            get {
                return NodeStyle.Minimalistic;
            }
        }
    }
    
    public class SystemNodeViewModelBase : uFrame.Editor.GraphUI.ViewModels.GenericNodeViewModel<uFrame.Editor.Graphs.Data.GenericNode> {
        
        public SystemNodeViewModelBase(SystemNode graphItemObject, uFrame.Editor.GraphUI.ViewModels.DiagramViewModel diagramViewModel) : 
                base(graphItemObject, diagramViewModel) {
        }
        
        public override uFrame.Editor.Platform.NodeStyle NodeStyle {
            get {
                return NodeStyle.Minimalistic;
            }
        }
    }
    
    public class EntityNodeViewModelBase : uFrame.Editor.GraphUI.ViewModels.GenericNodeViewModel<uFrame.Editor.Graphs.Data.GenericNode> {
        
        public EntityNodeViewModelBase(EntityNode graphItemObject, uFrame.Editor.GraphUI.ViewModels.DiagramViewModel diagramViewModel) : 
                base(graphItemObject, diagramViewModel) {
        }
        
        public override uFrame.Editor.Platform.NodeStyle NodeStyle {
            get {
                return NodeStyle.Normal;
            }
        }
    }
    
    public class ColorNodeViewModelBase : LiteralNodeViewModel {
        
        public ColorNodeViewModelBase(ColorNode graphItemObject, uFrame.Editor.GraphUI.ViewModels.DiagramViewModel diagramViewModel) : 
                base(graphItemObject, diagramViewModel) {
        }
        
        public override uFrame.Editor.Platform.NodeStyle NodeStyle {
            get {
                return NodeStyle.Normal;
            }
        }
    }
    
    public class EnumValueNodeViewModelBase : LiteralNodeViewModel {
        
        public EnumValueNodeViewModelBase(EnumValueNode graphItemObject, uFrame.Editor.GraphUI.ViewModels.DiagramViewModel diagramViewModel) : 
                base(graphItemObject, diagramViewModel) {
        }
        
        public override uFrame.Editor.Platform.NodeStyle NodeStyle {
            get {
                return NodeStyle.Minimalistic;
            }
        }
    }
    
    public class SequenceItemNodeViewModelBase : uFrame.Editor.GraphUI.ViewModels.GenericNodeViewModel<uFrame.Editor.Graphs.Data.GenericNode> {
        
        public SequenceItemNodeViewModelBase(SequenceItemNode graphItemObject, uFrame.Editor.GraphUI.ViewModels.DiagramViewModel diagramViewModel) : 
                base(graphItemObject, diagramViewModel) {
        }
        
        public override uFrame.Editor.Platform.NodeStyle NodeStyle {
            get {
                return NodeStyle.Minimalistic;
            }
        }
    }
}
