// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace Example {
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;
    
    
    public class LevelSelectScreenControllerBase : SubScreenController {
        
        private uFrame.MVVM.ViewModels.IViewModelManager _LevelSelectScreenViewModelManager;
        
        [uFrame.IOC.InjectAttribute("LevelSelectScreen")]
        public uFrame.MVVM.ViewModels.IViewModelManager LevelSelectScreenViewModelManager {
            get {
                return _LevelSelectScreenViewModelManager;
            }
            set {
                _LevelSelectScreenViewModelManager = value;
            }
        }
        
        public IEnumerable<LevelSelectScreenViewModel> LevelSelectScreenViewModels {
            get {
                return LevelSelectScreenViewModelManager.OfType<LevelSelectScreenViewModel>();
            }
        }
        
        public override void Setup() {
            base.Setup();
            // This is called when the controller is created
        }
        
        public override void Initialize(uFrame.MVVM.ViewModels.ViewModel viewModel) {
            base.Initialize(viewModel);
            // This is called when a viewmodel is created
            this.InitializeLevelSelectScreen(((LevelSelectScreenViewModel)(viewModel)));
        }
        
        public virtual LevelSelectScreenViewModel CreateLevelSelectScreen() {
            return ((LevelSelectScreenViewModel)(this.Create(Guid.NewGuid().ToString())));
        }
        
        public override uFrame.MVVM.ViewModels.ViewModel CreateEmpty() {
            return new LevelSelectScreenViewModel(this.EventAggregator);
        }
        
        public virtual void InitializeLevelSelectScreen(LevelSelectScreenViewModel viewModel) {
            // This is called when a LevelSelectScreenViewModel is created
            viewModel.SelectLevel.Action = this.SelectLevelHandler;
            LevelSelectScreenViewModelManager.Add(viewModel);
        }
        
        public override void DisposingViewModel(uFrame.MVVM.ViewModels.ViewModel viewModel) {
            base.DisposingViewModel(viewModel);
            LevelSelectScreenViewModelManager.Remove(viewModel);
        }
        
        public virtual void SelectLevelHandler(SelectLevelCommand command) {
            this.SelectLevel(command.Sender as LevelSelectScreenViewModel, command.Argument);
        }
        
        public virtual void SelectLevel(LevelSelectScreenViewModel viewModel, LevelDescriptor arg) {
        }
    }
}
