// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace uFrame.ECS.Editor {
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;
    using uFrame.Editor.Configurations;
    using uFrame.Editor.Core;
    using uFrame.Editor.Graphs.Data;
    
    
    public class DataGraphBase : GenericGraphData<DataNode> {
    }
    
    public class LibraryGraphBase : GenericGraphData<LibraryNode> {
    }
    
    public class ModuleGraphBase : GenericGraphData<ModuleNode> {
    }
    
    public class HandlerGraphBase : GenericGraphData<HandlerNode> {
    }
    
    public class SystemGraphBase : GenericGraphData<SystemNode> {
    }
}
